scripts/zowe-install-iframe-plugin.sh
Signed-off-by: stevenhorsman-ibm <steven@uk.ibm.com>
=> Add initial script for creating iframe plugin to zlux

scripts/zowe-init.sh
=> issue #18: validate existing NODE/JAVA environment value

install/zowe-install.sh, scripts/zowe-api-mediation-configure.sh, scripts/zowe-install-liberty-server.sh
Signed-off-by: stevenhorsman-ibm <steven@uk.ibm.com>
=> Add ZOWE_JAVA_HOME logging

scripts/zowe-init.sh
=> rtc defect 20719: touch correct .profile

scripts/zowe-api-mediation-configure.sh
Signed-off-by: stevenhorsman-ibm <steven@uk.ibm.com>
=> Create static defs folder and inject variable

Jenkinsfile, install/zowe-install.sh, install/zowe-install.yaml, scripts/zowe-install-iframe-plugin.sh, scripts/zowe-parse-yaml.sh
=> bump to 0.9.1

artifactory-download-spec.json, scripts/zowe-api-mediation-configure.sh
This PR includes the new API Catalog UI and static APIs support to the APIML.
=> Static API directory and latest APIML with new API Catalog

artifactory-download-spec.json
Signed-off-by: Mark Ackert <Mark.Ackert@ca.com>
=> Add Zowe CLI Bundle 0.9.1

artifactory-download-spec.json
Signed-off-by: Mark Ackert <Mark.Ackert@ca.com>
=> Update license references to 0.9.1 in artifactory

artifactory-download-spec.json
=> issue #30 migrate to zowe repository

files/templates/server.xml.template
=> Include languages file for editor

artifactory-download-spec.json
Signed-off-by: Mark Ackert <Mark.Ackert@ca.com>
=> Update cli bundle version

files/plugins/explorer-JES/web/index.html, files/plugins/explorer-MVS/web/index.html, files/plugins/explorer-USS/web/index.html
=> Need to update MVD references to revised explorers uri

Jenkinsfile, artifactory-download-spec.json, install/zowe-install.sh, install/zowe-install.yaml, scripts/zowe-install-iframe-plugin.sh, scripts/zowe-parse-yaml.sh
=> increase version to 0.9.3

scripts/zowe-api-mediation-configure.sh
=> Add apidef files for Atlas

Jenkinsfile
=> issue #130 verify download/upload result

scripts/zowe-api-mediation-configure.sh
Separate commits as I had to merge in Gateway script changes along the way
=> Atlas catalog integration

files/templates/server.xml.template
Upated server.xml based on the git issue encountered by customers
https://github.com/zowe/explorer-server/issues/21
=> Fix runaway CPU for ZOWESVR3

install/zowe-install.sh, manifest.json
=> bump to v0.9.4

scripts/zowe-api-mediation-configure.sh
=> Remove USS static definition from install

scripts/zowe-api-mediation-configure.sh
=> If opercmd can't be run then default doc link to latest release

install/zowe-install.sh, scripts/zowe-verify-post-install.sh
=> zowe-post-verify

install/zowe-pre-install.sh
=> Add pre-install script

Jenkinsfile, artifactory-download-spec.json.template
=> Remove Zowe CLI from package

artifactory-download-spec.json.template
=> update zlux version (fix terminal apps)

install/zowe-verify-pre-install.sh, scripts/zowe-verify-post-install.sh
=> update verify scripts

scripts/zowe-verify-post-install.sh
Pre-pend result msgs to the user with 'info', 'error', 'warning'
=> Add info/warning/error to user msgs

manifest.json
=> update verstion to 0.9.5

scripts/zowe-verify-post-install.sh
=> Discover ZOWESVR proc name without user input

scripts/zowe-parse-yaml.sh
=> Set omitted YAML defaults

scripts/zlux-install-script.sh
=> issue #180 fix permission denied error

artifactory-download-spec.json.template, install/zowe-install.yaml.template, scripts/zowe-api-mediation-configure.sh, scripts/zowe-api-mediation-install.sh, scripts/zowe-parse-yaml.sh
This PR contains changes of Zowe installation for:
- https://waffle.io/zowe/api-layer/cards/5bdbf8964e42c0006308be41
- https://waffle.io/zowe/api-layer/cards/5bd8be80283e09001babbf86
The documentation is in:
- https://github.com/zowe/docs-site/compare/apiml-https#diff-631b43e6cb2233eb3ef020fd5dfff2f3
- https://github.com/zowe/docs-site/blob/apiml-https/docs/guides/api-mediation-security.md
Depends on https://github.com/zowe/api-layer/pull/152
Update https://github.com/zowe/zowe-install-packaging/pull/184/files#diff-ca7c2d94ae4836f55a26e03644dfab37R15 after https://github.com/zowe/api-layer/pull/152 is merged to master
=> Certificate settings

artifactory-download-spec.json.template
=> update to use mfaas release build

scripts/zowe-api-mediation-configure.sh
=> Set all APIML Jars to a+rx

install/zowe-check-prereqs.sh, install/zowe-install.sh, scripts/zowe-troubleshoot.sh, scripts/zowe-verify.sh
=> Git issue 186

install/zowe-install.sh, scripts/zowe-api-mediation-configure.sh
=> Fix catalog plugin order

scripts/zowe-api-mediation-configure.sh
Depends on https://github.com/zowe/api-layer/pull/166
=> Add ZOWE_ROOT_DIR variable to setup-apiml-certificates-template template

scripts/zowe-verify.sh
=> Handle userid not IZUSVR

install/zowe-check-prereqs.sh
=> set min free space to 650 MB

install/zowe-install.yaml.template, scripts/zowe-parse-yaml.sh, scripts/zowe-zlux-configure-ports.sh
=> set tn3270 security type

scripts/zowe-prepare-runtime.sh
=> use Zowe IP address instead of hostname in web index.html

manifest.json
=> bump to v0.9.6

scripts/zowe-parse-yaml.sh
=> add missing fi

scripts/zowe-explorer-ui-install.sh
=> remove uneccessary rm

artifactory-download-spec.json.template, scripts/zowe-api-mediation-configure.sh
The test build passed smoke tests:
https://wash.zowe.org:8443/job/zowe-install-test/job/master/193/console
https://wash.zowe.org:8443/job/zowe-install-test/job/master/194/console
Please verify.
=> Point JES Explorer UI to new Jobs API

scripts/zowe-api-mediation-configure.sh
Simplifies the tiles in the catalog
=> remove orion and trim uss

Jenkinsfile, artifactory-download-spec.json.template, install/zowe-install.yaml.template, scripts/run-zowe.sh, scripts/zowe-api-mediation-configure.sh, scripts/zowe-explorer-api-configure.sh, scripts/zowe-explorer-api-install.sh, scripts/zowe-parse-yaml.sh
The zowe build `libs-snapshot-local/com/project/zowe/0.9.6-ISSUE-217/zowe-0.9.6-20190112.090638-5.pax` has datasets api packaged and can be started.
=> Issue #217: add data sets api into zowe build

install/zowe-install.sh, scripts/run-zowe.sh, scripts/zlux-install-script.sh, scripts/zowe-install-iframe-plugin.sh, scripts/zowe-prepare-runtime.sh, scripts/zowe-runtime-authorize.sh, scripts/zowe-verify.sh, scripts/zowe-zlux-configure-certificates.sh, scripts/zowe-zlux-configure-ports.sh, tests/test_zowe-zlux-configure-certificates.py
Reverts zowe/zowe-install-packaging#241
=> Revert "Fix zlux paths upon server rename"

artifactory-download-spec.json.template, install/zowe-install.sh, scripts/zowe-install-existing-plugin.sh, scripts/zowe-zlux-configure-ports.sh
This PR uses the new minor version of APIML `0.4.x` which includes the authentication service based on z/OSMF.
The authentication plugin is added to the zLUX during installation and it does the authentication using APIML.
The APIML token is stored in zLUX session and it is passed to the API catalog when it opened.
=> Includes APIML authentication plugin to Zowe zLUX

manifest.json
=> update manifest to 1.0.0

scripts/zowe-start.sh, scripts/zowe-stop.sh
=> Remove explorer-server from zowe-start.sh

scripts/zowe-explorer-api-configure.sh
=> issue #259 fix api installation

pax-workspace/pre-packaging.sh
=> add +x opercmd, ocopyshr.clist

artifactory-download-spec.json.template
=> include latest zlux build - with directory updates

install/zowe-install.sh
Signed-off-by: Petr Plavjanik <petr.plavjanik@broadcom.com>
=> Rename zlux-example-server to zlux-app-server in zowe-install.sh

scripts/zowe-explorer-ui-configure.sh, scripts/zowe-init.sh, scripts/zowe-parse-yaml.sh
Fix of the incorrect pull request https://github.com/zowe/zowe-install-packaging/pull/275 that @jackjia-ibm identified was behind master (sorry about that).  This is a fresh branch off master with the three file changed.
=> Correctly merged up to date with master for less chatty console

artifactory-download-spec.json.template
=> switch to explorer-jes 0.0.3 to pickup username parsing fix

artifactory-download-spec.json.template
=> update explorer api package

artifactory-download-spec.json.template
Signed-off-by: jordan cain <jordan.cain1@uk.ibm.com>
=> increase versions for jes and mvs to pickup bug fixes and features

artifactory-download-spec.json.template
Signed-off-by: jordan cain <jordan.cain1@uk.ibm.com>
=> Pick Up dialog+saveAs bug for uss, checksum->Etag for mvs

artifactory-download-spec.json.template
=> bump version

artifactory-download-spec.json.template
=> Update zip to take latest UI build

scripts/zowe-api-mediation-configure.sh
https://github.com/zowe/zowe-install-packaging/issues/315
=> Update reference number to 1.0.0

artifactory-download-spec.json.template
=> mvs version to pickup no dataset found message

scripts/zowe-runtime-authorize.sh
=> zlux-app-server/deploy permissions changed for clean install

artifactory-download-spec.json.template
=> Pickup latest jes explorer build - fix for unauthorized spool access notification

scripts/zlux-install-script.sh, scripts/zowe-verify.sh
Depends on https://github.com/zowe/zlux/pull/70
=> Removing references to missing directory zos-subsystems

artifactory-download-spec.json.template
=> Bump uss explorer to pickup auto remove trailing slash on fetches

artifactory-download-spec.json.template
=> pick most recent v0.0.x of explorer ui plugins

artifactory-download-spec.json.template
=> Update ZSS and ZLUX versions

artifactory-download-spec.json.template
=> Update ZSS version to pick up upload functionality fix

artifactory-download-spec.json.template
=> Update ZSS to new version

scripts/zowe-runtime-authorize.sh
=> deploy permission widening

scripts/zowe-init.sh
=> Fix error of non-existing zowe_profile

scripts/zowe-runtime-authorize.sh
=> 775 and 555 to give read and traverse authority

scripts/zowe-runtime-authorize.sh
=> chgrp IZUADMIN for zlux-app-server/deploy

.gitignore, Jenkinsfile
=> add explorer builds to upstream

artifactory-download-spec.json.template
=> update zss version

scripts/zowe-runtime-authorize.sh
=> remove x permission for files in serverConfig

scripts/zowe-runtime-authorize.sh
=> check if folder is empty before chmod

scripts/zowe-verify.sh
Update the number of processes per ZOWESVRn job and update which ports are assigned to which job, to reflect the latest configuration.
=> Update process and port numbers for ZOWESVR jobs

manifest.json.template
=> Set Zowe version to 1.0.1

scripts/zowe-explorer-ui-configure.sh
=> replace csp frame-ancestors config

artifactory-download-spec.json.template
=> Update ZSS & zLUX version for 1.0.1

scripts/zowe-api-mediation-configure.sh
=> Change api def to include unix file endpoint

scripts/zowe-api-mediation-configure.sh
=> Add unix files under seperate serviceId

Jenkinsfile
=> allow to assign pax server port

artifactory-download-spec.json.template
=> Update api version requirements

artifactory-download-spec.json.template
=> pulling the most recent explorer api builds of v0.1.x

artifactory-download-spec.json.template
=> jobs api has new minor level release

install/zowe-check-prereqs.sh
=> Don't prompt if ssh and telnet in use

Jenkinsfile
=> support branch name with slashes

artifactory-download-spec.json.template
=> Use zlux-core v1.1.0

artifactory-download-spec.json.template
Signed-off-by: Seva Khanin <vsevolod.khanin@broadcom.com>
=> mfaas-zowe-isntall version updated to 1.1.*

install/zowe-check-prereqs.sh
=> check ICSF before node

artifactory-download-spec.json.template
=> Update datasets version

artifactory-download-spec.json.template, manifest.json.template
This is a replacement of https://github.com/zowe/zowe-install-packaging/pull/451
=> Node cluster staging

install/zowe-check-prereqs.sh, scripts/zowe-init.sh
=> Warn hostname ip

artifactory-download-spec.json.template
=> Update zLUX / ZSS artifacts

artifactory-download-spec.json.template
=> Update zlux-editor arifact

scripts/zowe-verify.sh
Check the following ZSS server items
- Is program ZWESIS01 running?
- Is program ZWESIS01 running under user IZUSVR?
- Try to determine ZSS server job name
- Is ZSS server job running as a STC?
- Is the status of the ZSS server OK in the zssServer log in this ZOWE_ROOT_DIR?
=> Add check of ZSS to zowe-verify script

artifactory-download-spec.json.template, scripts/zowe-init.sh, scripts/zowe-verify.sh
=> check hostname resolves to IP address

dco_signoffs/Craig-Forrest-zowe-install-packaging.txt
Signed-off-by: Craig-Forrest <Craig.Forrest@ibm.com>
=> add dco signoff

files/zlux/config/zluxserver.json
=> Update zLUX default config

artifactory-download-spec.json.template
=> Update zLUX artifacts

.gitignore, .pax/pre-packaging.sh, .pax/prepare-workspace.sh, Jenkinsfile, artifactory-download-spec.json.template
=> Apply new jenkins library

install/zowe-install.sh, install/zowe-install.yaml.template, scripts/run-zowe.sh, scripts/zowe-parse-yaml.sh, scripts/zowe-verify.sh
Rework of #499 &ndash; change branch `master` &rarr; `staging`
- New configuration parameter `prefix`
- Add component codes from [#385](https://github.com/zowe/zowe-install-packaging/issues/385#issuecomment-489555612) to each process
- Add facility check to `zowe-verify.sh`
=> Add started task names to Zowe USS processes

scripts/configure/zowe-configure-api-mediation.sh, scripts/configure/zowe-install-iframe-plugin.sh
=> Update permissions during configure

manifest.json.template
=> Bump to 140

manifest.json.template
=> Update zLUX/ZSS source dependencies tags

manifest.json.template
Signed-off-by: MarkAckert <mark.ackert@broadcom.com>
=> update source tags for CLI 1.4.0 bundle

manifest.json.template
=> Update ZSS for v1.4.0 rc3

manifest.json.template
=> Update ZSS for v1.4.0 rc3 #2

manifest.json.template
=> Update zLUX Editor for v1.4.0 rc4

scripts/zowe-verify.sh
=> Check CIM server is running

scripts/zowe-init.sh
=> Remove spaces

install/zowe-install.sh, scripts/zowe-copy-xmem.sh
=> Tidy customise zss name

scripts/configure/zowe-configure.sh
=> Remove reference to old code

scripts/zowe-runtime-authorize.template.sh
=> Add g+w to zlux-app-server logs

manifest.json.template
=> Update zLUX and ZSS for v1.5.0

scripts/zowe-explorer-api-install.sh
=> Only inject root dir offset in install script

manifest.json.template
=> update zlux versions

manifest.json.template
=> Update zLUX and ZSS for v1.5.0 RC2

smpe/bld/get-config.sh, smpe/bld/smpe-install.sh
=> minor cleanup

manifest.json.template
=> Update zLUX and ZSS for v1.5.0 RC3

manifest.json.template
Signed-off-by: MarkAckert <mark.ackert@broadcom.com>
=> update tags for api-layer and cli

manifest.json.template
=> Update zLUX / ZSS 1.5.0 tags

smpe/pax/MVS/ZWE1SMPE.jcl, smpe/pax/MVS/ZWE2RCVE.jcl, smpe/pax/MVS/ZWE3ALOC.jcl, smpe/pax/MVS/ZWE4ZFS.jcl, smpe/pax/MVS/ZWE6DDEF.jcl, smpe/pax/MVS/ZWEMKDIR.rex, smpe/pax/MVS/ZWES0LST.jcl, smpe/pax/MVS/ZWES3APL.jcl, smpe/pax/MVS/ZWES4ACP.jcl, smpe/pax/USS/ZWESHPAX.sh, smpe/pax/scripts/allocate-dataset.sh, smpe/pax/scripts/check-dataset-exist.sh
=> remove pre-z/OS 2.1 comments & trim trailing blanks

Jenkinsfile.release
=> add signing key info to the build

manifest.json.template
=> bump to 1.6.0

install/zowe-install-apf-server.sh
=> Update ZIS installation to pick up ZWESAUX

Jenkinsfile.release
=> missing quotes

install/zowe-install.sh
=> Add missing shebang

scripts/run-zowe.template.sh
=> Added export __UNTAGGED_READ_MODE=v6 to Zowe startup

files/zlux/config/plugins/org.zowe.zlux.ng2desktop.settings.json
Signed-off-by: Suneeth Keerthy <skeerthy@rocketsoftware.com>
=> Added ng2desktop settings to plugin list

smpe/bld/alter.sh
=> remove uneeded code

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Signed-off-by: nannanli <nannanli@cn.ibm.com>
This PR defines a template for the Pull Requests. It will require submitter to fill in some information to help us automate some processes like the release notes generation.
=> Create a Pull Request template

manifest.json.template
=> Update zLUX and ZSS for 1.7.0

bin/zowe-configure-instance.sh, scripts/instance.template.env
=> Refactor keystore parms

bin/internal/run-zowe.sh, bin/zowe-configure-instance.sh, scripts/configure/zowe-configure.sh
=> Yaml speciality mode

Jenkinsfile.nightly, Jenkinsfile.release
Fixes #871
- Remove publish stage during release.
=> remove publishing to projectgiza.org

manifest.json.template
=> bumped ZSS to 1.7.1

bin/zowe-configure-instance.sh
Fixed logic when creating a new instance in an existing directory
=> Better logic for handling exisiting instance_dirs

manifest.json.template
=> Bump zss to 1.8.0

bin/internal/run-zowe.sh, install/zowe-install.yaml.template, scripts/instance.template.env
Add documentation to try and help address #866
=> Add comment explaining tn3270 connection security

Jenkinsfile, Jenkinsfile.nightly, Jenkinsfile.release, manifest.json.template
Fixes https://github.com/zowe/zowe-install-packaging/issues/875
- Migrate to LF sponsored Artifactory.
---
---
---
---
=> switch to zowe artifactory

.pax/catchall-packaging.sh
=> put tsocmd to background

install/zowe-install-apf-server.sh
=> Update names to match zss pax

bin/internal/run-zowe.sh, bin/zowe-configure-instance.sh, scripts/configure/zowe-configure.sh
=> Temp: 777 logs until we can chgrp post 518

scripts/zowe-install-MVS.sh
Fix regression introduced in #958
=> Remove excessive pruning

bin/zowe-init.sh
=> Fix bad copyos

bin/utils/zowe-install-iframe-plugin.sh
=> Update iframe-plugin to use moved script

smpe/bld/smpe-service.sh
Fixes 999
- fixed typo blocking PTF inclusion
---
---
---
---
=> typo prevents PRE(ptf) for APAR & USERMOD

files/jcl/ZWESECUR.jcl
- [y ] Bugfix 
Fixes 
- Remove the keyword ALL from the LISTGRP commands
- [x ] No
---
RACF security check during install
---
---
---
Doc issue/PR …
=> ZWESECUR JCL has superfluous keyword ALL in the LISTGRP commands

scripts/zowe-install-MVS.sh, smpe/ZOSMF/vtls/ZWE3ALOC.vtl
Adjust loadlib blocksize to match IBM packaging rule that checks for optimal size
Fixes 
- Adjust loadlib blocksize to match IBM packaging rule that checks for optimal size
---
---
---
* Part: _name of …
=> adjust blocksize to match IBM packaging rule

install/zowe-install.sh
Fixes 
- error message for faulty startup argument uses wrong variable, so you don't see which startup argument triggered the error
---
---
---
--- …
=> zowe-install.sh uses wrong variable to report argument error

scripts/utils/zowe-copy-to-JES.sh
- [y ] Bugfix 
Fixes #1034
The editing of the JCL member in `zowe-copy-to-JES.sh` is corrected to use the PARMLIB instead of the SAMPLIB as the replacement
---
XMEM server
---
Now has correct PARMLIB DSN
---
---
_multi-line …
=> Edit samplib to parmlib in XMEM JCL

bin/internal/run-zowe.sh, bin/zowe-configure-instance.sh, install/zowe-install.sh
=> Add new statements

install/zowe-check-prereqs.sh, scripts/utils/validate-node.sh
=> Simplify and reuse code

files/jcl/ZWENOSEC.jcl, files/jcl/ZWESECUR.jcl
Fixes 1044
- ensure last command in ZWESECUR/ZWENOSEC returns RC 0
---
---
---
---
=> ensure ZWESECUR/ZWENOSEC RC is 0 as documented

shared/scripts/allocate-dataset.sh, shared/scripts/check-dataset-dcb.sh, smpe/bld/smpe-fmid.sh, smpe/bld/smpe-install.sh
- allocate RELFILEs with a given block size
- remove install_log from SMPE input staging area
Fixes 1045
- allocate RELFILEs with a given block size
- remove install_log from SMPE input staging area
---
--- …
=> allow fixed block sizes & clean up install_log

bin/internal/run-zowe.sh, bin/zowe-configure-instance.sh, scripts/utils/validate-port-available.sh
=> Instance dir cleanup

scripts/utils/zowe-install-proc.sh
Resolves #1086 
Reduces the noise that echos to stdout
=> Remove debug/logs echoing to stdout

bin/internal/run-zowe.sh, bin/internal/zowe-set-env.sh, bin/zowe-configure-instance.sh, bin/zowe-support.sh, install/zowe-check-prereqs.sh, install/zowe-install.sh
Create a single script with envinronments required to support node 12
=> WIP: Set env.sh & node 12

bin/internal/run-zowe.sh
=> Change variable to LAUNCH_COMPONENT

smpe/ZOSMF/vtls/ZWE1SMPE.vtl, smpe/ZOSMF/vtls/ZWE1SMPE.yml, smpe/bld/AZWE001.htm, smpe/bld/smpe-pd.sh
* add Zowe program directory to build output
* Zowe now only installs in 1 SREL, so ZWE1SMPE must be adjusted to match
Fixes 1105
- add Zowe program directory to build output
- Zowe now only installs in 1 SREL, so ZWE1SMPE must be adjusted to match
---
---
---
* Part: …
=> single SREL for ZWE1SMPE & add actual Zowe PD

manifest.json.template
=> bump Zowe version

manifest.json.template
=> Zowe release 1.9.0

install/zowe-check-prereqs.sh
=> Remove set -e

manifest.json.template
=> Updated zss missing file

bin/zowe-init.sh, bin/zowe-setup-certificates.sh
Use getopts
- Disable node check in zowe-setup-certificates.sh
=> Use getopts

manifest.json.template
Fixes 
- APIML has changed release path from `com.ca.mfaas.sdk.mfaas-zowe-install` to `org.zowe.apiml.sdk.zowe-install` as of `v1.3.0`.
---
---
---
---
_multi-line …
=> pick up new apiml versions

install/zowe-install.sh
Fixes #1117 
Tidy up of unused file
=> Remove jcl copy

files/jcl/ZWESECUR.jcl
Fixes 
https://github.com/zowe/zowe-install-packaging/issues/1039
Doc issue/PR number: 
https://github.com/zowe/docs-site/pull/1026
=> remove block with TSS multi-user address space

bin/zowe-setup-certificates.env
usability enhancement
Fixes 
- wrap zowe-setup-certificates.env comments at col 72 for ISPF
---
---
---
---
=> wrap comments at col 72 for ISPF

bin/zowe-setup-certificates.sh
The zowe-setup-certificates.sh script now fails if the trust-zosmf action fails.
Fixes 
https://github.com/zowe/zowe-install-packaging/issues/1132
Doc issue/PR number: 
https://github.com/zowe/docs-site/pull/1041
=> The zowe-setup-certificates.sh script now fails if the trust-zosmf action fails

bin/internal/run-zowe.sh
#1144 but for staging instead of RC
=> Backwards compatible path for read-instance.sh

bin/internal/zowe-set-env.sh
This addresses https://github.com/zowe/zowe-install-packaging/issues/1141
May need to revisit in 1.10 to see if we need a refinement and different permissions for different areas.
=> Allow group write as user write already existed

manifest.json.template
=> updated zss

bin/zowe-configure-instance.sh
- Add validation check to stop user error
Fixes #1123 
Check that the user isn't trying to checking the instance directory inside the runtime directory
=> Add check for instance in root directory

manifest.json.template
Update manifest.json.template to set licenses to 1.9.0
=> Zowe 1.9.0 license update

manifest.json.template
Set staging licenses to 1.9.0.
=> set licenses to 1.9.0

manifest.json.template
This PR brings zlux to the most recent versions after v1.9.0 release.
- 
---
---
---
---
=> update zlux version for staging

files/zlux/config/plugins/org.zowe.zlux.auth.zosmf.json
Full explanation here: https://github.com/zowe/zlux/issues/398
=> Do not register extra auth plugin by default

smpe/bld/service/fixed-hold-ACTION.txt, smpe/bld/service/ptf-bucket.txt
Fixes 
- correct started task names in fixed HOLD data.
---
---
---
---
=> update STC name in hold info

shared/scripts/allocate-dataset.sh, smpe/bld/get-config.sh, smpe/bld/smpe-service.sh
Fixes 
- Add support for SMS-managed multi-volume allocations to allocate-dataset.sh, and give smpe-service.sh a variable to use this if needed.
---
---
---
---
=> support multi-volume GIMDTS alloc

smpe/bld/smpe-service.sh
Fixes 
- binary MVS to USS copy of PTF
---
---
---
---
=> binary PTF copy

manifest.json.template
=> prepare for v1.10.0

Jenkinsfile.nightly, Jenkinsfile.release, tests/installation/Jenkinsfile
Fixes 
- Add job description to test/promote nightly/release pipelines to show purpose of the job.
---
---
---
---
=> update job description to provide hint of the job

manifest.json.template
=> Update artifact ref for zlux, zss

smpe/bld/ptf.readme.htm
Add comment to PTF install instructions to remove CHECK to do actual APPLY
Fixes 
- Add comment to PTF install instructions to remove CHECK to do actual APPLY
---
---
---
---
=> APPLY CHECK comment

manifest.json.template
=> Fixed staging version

tests/sanity/test/e2e/test-01-login.js, tests/sanity/test/e2e/test-06-vt.js, tests/sanity/test/e2e/utils.js
Fixes nightly build test failure on desktop. It failed to find the login button.
- Switch to use class name instead of element ID after the ID is removed.
---
---
--- …
=> login button id is removed, use class name instead

manifest.json.template
=> pick data set v1

playbooks/roles/configfmid/tasks/install_xmem_server.yml
Fixes the parmlib created as time going will become full.
- 
---
---
---
---
=> change to pdse so the space can be recycled

tests/sanity/test/cli/test-01-version.js, tests/sanity/test/cli/test-02-zosmf.js, tests/sanity/test/cli/test-03-jobs.js, tests/sanity/test/cli/test-04-files.js
=> disable addContext on cli testing

bin/internal/zowe-set-env.sh
Fixes error:
```
msgget: EDC5133I No space left on device. (errno2=0x07050305)
CEE5207E The signal SIGABRT was received.
Ended with rc=131
```
- Always set `__IPC_CLEANUP=1`.
---
---
---
* Part: _name of customizable …
=> always set __IPC_CLEANUP=1

tests/installation/Jenkinsfile, tests/installation/src/__tests__/extented/node-versions/node-v12.ts, tests/installation/src/__tests__/extented/node-versions/node-v8.ts
Fixes 
- Add node.js v12.16.1 to test options
---
---
---
---
=> add node.js v12.16.1 to test options

manifest.json.template
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._
=> prepare for v1.11.0

tests/sanity/test/e2e/test-11-workflows.js, tests/sanity/test/e2e/utils.js
Fixes test cases after Workflow App has been removed from Desktop.
- Skip workflow test.
=> workflow app is not started by default

files/zlux/config/plugins/org.zowe.zosmf.workflows.json, tests/sanity/test/e2e/test-11-workflows.js, tests/sanity/test/e2e/utils.js
Fixes the test failure on PTF which workflow app is still showing.
- Add workflow app back.
=> add workflow desktop app back

Jenkinsfile.nightly
Signed-off-by: MarkAckert <mark.ackert@broadcom.com>
Fixes nightly build - was publishing 2x Zowe CLI Plugins instead of 1x Zowe CLI Core and 1x Zowe CLI Plugins
=> Fix CLI Package Nightly Publish

manifest.json.template
=> Updated sourceDependencies

manifest.json.template
Update release candidate license to v1.11.0.
=> update license to v1.11.0

tests/sanity/test/e2e/test-02-jes-explorer.js, tests/sanity/test/e2e/test-03-mvs-explorer.js, tests/sanity/test/e2e/test-04-uss-explorer.js
Fixes 
- Fix MVS Explorer test
---
---
---
---
=> Rename css paths to comply with updated MVS explorer component

bin/internal/run-zowe.sh, bin/internal/zowe-set-env.sh, scripts/utils/cleanup-ipc-mq.sh
Always export __IPC_CLEANUP=1 caused another problem which the node.js process may randomly hang on __getipc().
- Remove __IPC_CLEANUP environment variable.
- Manually clean up IPC message queue.
=> manually cleanup ipc message queue other than __IPC_CLEANUP

bin/zowe-init.sh
Fixes  #1279 IPV6 error
- ping returns different format in IPV6 environment.  This change forces the format in IPV6 environment to be the same as IPV4.
- ping, or its equivalent, is used to derive the full hostname and IP address on the customer system.  Both cases are amended.  
This corrects an error during `zowe-int.sh` when the customer creates a zowe …
=> Force ping format to IPV4

bin/zowe-init.sh
Related to https://github.com/zowe/zowe-install-packaging/pull/1352
For keystore generation, the code in 1352 helped but there was one last place that needed updating for keystores to work again on my system.
=> One more ipv4 place to update

tests/sanity/test/install/test-file-utils.js
Fixes #1377 
- Skip tests that Marist's ACF2 and TS configuration is not configured correctly for
=> zip 1377 - Skip tests that marist has problems with

Jenkinsfile.nightly
Fixes 
- Test nightly build on all security systems other than just RACF.
=> test nightly with bundle of all security systems

bin/utils/node-utils.sh
Fixes 
- Currently zowe-init.sh makes a call to a none existent function line 149: prompt_for_node_home_if_required), rename the function so that call is correct
---
---
---
* Part: _name of customizable file involved_ …
=> Rename function for checking and prompting node home

manifest.json.template
=> Setting manifest back to use staging

tests/sanity/test/apiml/test-authentication-zosmf-via-gateway.js, tests/sanity/test/apiml/test-jes-via-gateway.js, tests/sanity/test/apiml/test-mvs-via-gateway.js, tests/sanity/test/apiml/utils.js
Improval of the test suite to catch potential integration issues earlier.
https://github.com/zowe/zowe-install-packaging/issues/1292
The API Mediation Layer squad provides further tests for nightly builds to verify integration with other Zowe components:
Retrieval of data from MVS via Gateway
Retrieval of jobs from MVS via Gateway
Authentication calls to …
=> Add safe tests for Sanity testing

tests/sanity/package-lock.json, tests/sanity/test/e2e/test-01-login.js, tests/sanity/test/e2e/utils.js
Fixes failed test cases after desktop UI upgrade.
=> fix failed test cases after desktop ui upgrade

manifest.json.template, tests/sanity/test/apiml/test-login-to-system-and-logout.js
Added smoke tests for Logout
Add smoke tests for the Logout functionality
No
=> Add verification for Logout methods to Nightly build

playbooks/group_vars/zoweNode.yml
Add an ansible variable for zowe cicd.
- Add variable for zowe cicd 
---
---
---
---
=> Added varible zos_zosmf_port=443 for zowe cicd pipeline

manifest.json.template
=> Fix for missing files

bin/zowe-setup-certificates.sh
=> Export external root CA to env variable - target to rc

manifest.json.template
=> Fix for terminals RC2

bin/zowe-setup-certificates.sh
=> External root ca

bin/zowe-setup-certificates.sh
=> Pass the local_ca_filename" prefix as an argument to apiml_cm.sh

smpe/bld/service/current-hold-ACTION.txt
Fixes 
- 1.12 is a breaking upgrade, so HOLD info must be added. Automation to pull this from existing pull request is not yet in place, so we're adding it manually.
---
---
---
* Part: _name of …
=> add 1.12 hold info

manifest.json.template
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._
=> Prepare for v1.13.0 as it's confirmed to be next release

manifest.json.template
Update CLI anmd VSCode Extension versions for Zowe 1.13.0
=> cli and vscode versions

manifest.json.template
Update snapshot version of apiml because of new release.
Fixes 
- 
---
---
---
---
=> higher snapshot version

manifest.json.template
- Update manifest version for Explorer web ui components & apiml
=> Update binary and source dependencies

manifest.json.template
=> Zowe RC for 1.13.0

manifest.json.template
=> temporarily set zlux branch to rc for source scan

manifest.json.template
=> bumped version to 1.13

playbooks/roles/ptf/files/jcl/Z1ALLOC.jcl, smpe/bld/smpe-service.sh
Fixes 1459
- update hardcoded PTF allocation size in Z1ALLOC.JCL (part of unit test) to use max PTF size and avoid out-of-space abends
---
---
---
--- …
=> update hardcoded space allocation for unit test

playbooks/roles/ptf/files/jcl/Z1ALLOC.jcl, smpe/bld/smpe-service.sh
=> Update track size in test

manifest.json.template
=> updated explorers to latest release version

scripts/zowe-install-api-mediation.sh
Fixes #1481 
- Remove install scripts of something that is now deleted.
=> Remove apliml-auth from install

manifest.json.template
=> Fix Editor Bug for RC

tests/installation/Jenkinsfile
The labeled lock doesn't really lock the resource, which results in 2 install tests may run at same time.
- lock with `resource` is working properly as tested.
=> fix issue on label lock doesn't work as documented

manifest.json.template
Update zlux source tags to 1.13 version now release is picked
=> Update zlux source tags to released version

manifest.json.template
=> Fix common c source tag

manifest.json.template
=> Update Zowe Version to 1.14.0

manifest.json.template
=> Upgrade staging to 1.14

bin/zowe-configure-instance.sh
Signed-off-by: Suneeth Keerthy <skeerthy@rocketsoftware.com>
Fixes 
- 
---
---
---
---
=> Added external instance option for docker images

bin/utils/zowe-install-iframe-plugin.sh, bin/zowe-configure-instance.sh, tests/sanity/test/install/test-install-iframe-plugin.js
Fixes #1425
- Update zowe-install-iframe-plugin.sh to convert it to getopts and thereby add support for more optional parameters, allowing the supply of version number as a parameter. Added tests for this.
=> Refactor zowe-install-iframe-plugin script and add tests

.pax/pre-packaging.sh, install/zowe-install.sh
Fixes #1527 
- moved fingerprinting to end of pre-packaging to ensure it picks up everything
- updated zowe-install.sh to copy workflows to ZOWE_ROOT_DIR/workflows
---
customization
---
add configuration …
=> quick fix for #1527 missing workflows

manifest.json.template
=> Updated to 1.14.0

files/jcl/ZWEKRING.jcl
(will do as part of S3, see ... https://github.com/zowe/zowe-install-packaging/issues/1535
Fixes https://github.com/zowe/zowe-install-packaging/issues/1562
This is the first release 1.14 that this JCL has been released in
=> ZWEKRING JCL to match default behavior of zowe-create-certificates.sh

manifest.json.template
Part of #1557 
- Update cli and vscode versions
=> Pick the latest cli tags

tests/sanity/test/e2e/test-01-login.js, tests/sanity/test/e2e/utils.js
Signed-off-by: Leanid Astrakou <lastrakou@rocketsoftware.com>
Adds some usage of QA ID's for the elements
This should be merged in combination with: https://github.com/zowe/zlux-app-manager/pull/270
Fixes 
- 
---
---
---
--- …
=> Update some virtual desktop tests to include ID's

playbooks/host_vars/tivlp46.yml, playbooks/host_vars/wlag.yml, playbooks/hosts
Adding new vms for zowe-ext pipeline
Fixes 
We have new vms need to be used in pipeline
---
---
---
---
=> Merge Zowe-ext to staging for adding new vms used in zowe pipeline

bin/apiml_cm.sh
=> create CA to encapsulate z/osmf JWT in a certificate

manifest.json.template
New RC required to include - https://github.com/zowe/zlux-server-framework/pull/239
Issue with casing have now been solved and incorporated into new zlux-core build.
=> Update manifest to include new zlux-core

manifest.json.template
=> cli versions

manifest.json.template
=> Bump Zowe Version to 1.15

tests/installation/package-lock.json, tests/sanity/package-lock.json, tests/sanity/package.json
Supercedes #1521 and #1520 
- Security fix in package.json
=> Bump lodash for security

tests/sanity/test/cli/test-05-console.js, tests/sanity/test/explorer/test-api-datasets.js, tests/sanity/test/explorer/test-api-jobs.js, tests/sanity/test/explorer/test-api-uss.js
Increase test coverage.
Fixes #1602
=> Added additional test cases

bin/apiml_cm.sh, bin/zowe-setup-certificates.sh
Fix for https://github.com/zowe/zowe-install-packaging/issues/1606
=> Fix: Error zowe-create-certificate.sh when GENERATE_CERTS_FOR_KEYRING=true

files/jcl/ZWEKRING.jcl, playbooks/roles/configure/tasks/create_keyring.yml
Extract hostname and ip address to SET variables
Fixes 
https://github.com/zowe/zowe-install-packaging/issues/1611
=> ZWEKRING: Extract hostname and ip address to SET variables

manifest.json.template
=> RC build for 1.15.0 

manifest.json.template
Signed-off-by: Jakub Balhar <jakub.balhar@broadcom.com>
=> Bump API ML version to 1.16.0-SNAPSHOT

manifest.json.template
=> fix keyring mode

playbooks/host_vars/tivlp46.yml, playbooks/host_vars/wlag.yml, playbooks/hosts
Updated some values for specific parameters for installing zowe on those VMs
Fixes 
- 
---
---
---
---
=> Updated some parameters for installing zowe on those systems

playbooks/README.md, playbooks/all_host_vars_list.yml, playbooks/install-ptf.yml, playbooks/roles/configfmid/defaults/main.yml, playbooks/roles/configfmid/tasks/main.yml, playbooks/roles/configure/defaults/main.yml, playbooks/roles/configure/tasks/main.yml
Fixes #1634 
- Add `zowe_configure_skip_zwesecur` Ansible variable to allow skipping ZWESECUR step
Updated README.md
=> issue #1634 option (zowe_configure_skip_zwesecur) to skip ZWESECUR step

manifest.json.template
part of #1640 
- Update zlux source tags
=> Update zlux source tags in 1.15 rc

tests/installation/src/__tests__/extended/keystore-modes/tss-keyring.ts
Implements #1636 
- Re-add tss tests after permissions change
=> Add tss test back in

manifest.json.template
Part of #1640 
- Update license version pulled in to release
=> Update license version

manifest.json.template
=> Bump staging to use newest app-server staging

tests/sanity/test/cli/test-07-tso.js
Added test cases that tests against tso cli commands within another PR (#1646) but the test cases hangs indefinitely, for now we will be skipping it and will investigate the issue until we find a solution. (Also removed the "noracf" option since it may be one of the main causes of the test case to run …
=> TSO-CLI test case is running indefinitely for some servers

manifest.json.template
Signed-off-by: at670475 <andrea.tabone@broadcom.com>
Fixes 
- 
---
---
---
---
=> Bump API ML version to 1.17.0-SNAPSHOT

manifest.json.template
=> Zowe 1.16 Release

manifest.json.template
Fixes 
- 
- add new shared folder with explorer-ui-server extracted out of three explorers.
https://github.com/zowe/explorer-ui-server/issues/36
=> update explorers to latest version in manifest

bin/utils/node-utils.sh, tests/sanity/test/install/test-node-utils.js
Fixes #1703 
- Remove code that specified different behaviour happening before and after 30/9/20
=> Remove date logic now node 6 support has ended

manifest.json.template
=> Fix Impersonation Error

bin/zowe-setup-certificates.sh
Signed-off-by: Suneeth Keerthy <skeerthy@rocketsoftware.com>
Fixes 
- 
---
---
---
---
=> Attempt to fix linux error

manifest.json.template
Part of #1721 
- Update app framework component source tags after release
=> Update source tags

bin/internal/run-zowe.sh
Implements #1412 
- Add ZWE_LAUNCH_COMPONENTS support in instance.env
=> Add ZWE_LAUNCH_COMPONENTS support

tests/sanity/test/e2e/test-02-jes-explorer.js
Fixes 
- 
---
---
---
---
Doc issue/PR number: 
Updated material ui library for jes and it broke the smoke tests.
=> update status-field selector

manifest.json.template
Fixes #1739 
- Increase version number
=> Bump verison number

.pax/pre-packaging.sh
Fixes #1531 
- Replace hard coded version number with the zowe version. This isn't perfect, but there is a large overlap between the api-ml version and overall zowe and we don't seem to have access to the correct version anywhere at this point.
=> Update fixed version number

.pax/pre-packaging.sh, smpe/bld/service/_README.txt, workflows/_README.txt
Fixes 
- minor updates to readme files
---
---
---
---
=> readme updates

CHANGELOG.md
Signed-off-by: nannanli <nannanli@cn.ibm.com>
Fixes 
- Made edits to the CHANGELOG content for v1.17
---
---
---
---
=> Update CHANGELOG for v1.17

tests/installation/src/constants.ts
- Increase convenience build overall timeout to cope with slow transfer speeds better
=> increase timeout to help with transfer delays

scripts/instance.template.env
Fixes 
Add property in the `instance.env` which allows to switch to different spring profiles (default is `DIAG`) in the API ML.
---
---
---
---
=> Add spring profile property for API ML

manifest.json.template
=> RC for 1.17

manifest.json.template
Signed-off-by: Jakub Balhar <jakub.balhar@broadcom.com>
The new API ML version was released.
=> Update to new version of API ML

manifest.json.template
Update version of Apiml in dependencies to include fix to turn off debug mode as the default
=> Update Apiml version

manifest.json.template
Part of #1789
- Update source dependency to match app framework release
=> Update source dependencies to match zlux release

playbooks/host_vars/marist-2.yml, playbooks/roles/configure/tasks/main.yml, playbooks/roles/zowe/defaults/main.yml
Signed-off-by: achmelo <a.chmelo@gmail.com>
1 task is failing on ACF2 in specific conditions, this will skip this task until the functionality is enabled on the system
Fixes 
- 
---
---
---
---
=> skip x509 related tasks if it is disabled on server

manifest.json.template
=> Upgarde Zowe Version to 1.18.0

.pax/prepare-workspace.sh, Jenkinsfile, manifest.json.template
Part of #1769
- Import zowe-install-packaging-tools into zowe build
=> download utility tools and put into bin/utils

playbooks/roles/configure/tasks/configure_sso_token.yml
Fixes issue on some servers CRYPTOZ is not enabled and `SETROPTS RACLIST(CRYPTOZ) REFRESH` will cause a failure.
- Enable `CRYPTOZ` profile before refresh commands.
=> enable CRYPTOZ profile

playbooks/host_vars/tivlp46.yml, playbooks/host_vars/tvt4188.yml, playbooks/host_vars/tvt5064.yml, playbooks/host_vars/tvt6019.yml, playbooks/host_vars/tvt6080.yml, playbooks/host_vars/vm30051.yml, playbooks/host_vars/wlag.yml
- [x ] DCO signoffs have been added to all commits, including this PR
- [ x] Other... Please describe:
Updated zowe test system yml files to support third-party certificate
Fixes 
- 
---
---
---
--- …
=> Update zowe test systems for running third-party certificate

bin/apiml_cm.sh, bin/zowe-setup-certificates.sh
Attempt to fix #1816 
- Add lots of double quotes to cope with variables having strings
=> Add lots of double quotes

manifest.json.template
PArt of #1789 
- Fix incorrect source version
=> Add v to version

manifest.json.template
=> Upgrade to 1.18 for release

Jenkinsfile, Jenkinsfile.nightly, Jenkinsfile.release, tests/installation/Jenkinsfile, tests/sanity/README.md
Part of https://github.com/zowe/zlc/issues/199
- Replace build agent label.
=> update build label name

bin/apiml_cm.sh
Fixes #1837 
- Correct gateway jar path in apiml_cm.sh
=> Fix gateway-jar path

tests/installation/Jenkinsfile, tests/installation/src/__tests__/extended/node-versions/node-v14.ts
- Cherry pick fix #1840 into rc branch.
=> Update node versions

Jenkinsfile, Jenkinsfile.release, playbooks/README.md, playbooks/roles/docker/defaults/main.yml
- Cherry pick in change from #1828 into rc branch
=> Bulk rename of zowe docker image from zowe-v1-lts to server-bundle

playbooks/host_vars/marist-1.yml, playbooks/roles/verify/defaults/main.yml
Cherry pick fix from #1845 into rc branch
=> Try to only run js test files

Jenkinsfile, Jenkinsfile.nightly, Jenkinsfile.release, playbooks/group_vars/marist.yml, tests/installation/Jenkinsfile
Test network connection issues.
- Use new jenkins agent located in WDC06.
=> prepare for new build agent in WDC06

.gitignore, .pax/prepare-workspace.sh, Jenkinsfile, bin/internal/global-validate.sh, bin/internal/prepare-environment.sh, bin/internal/prepare-workspace.sh, bin/internal/start-component.sh, bin/utils/common.sh, bin/utils/component-utils.sh, install/zowe-install.sh, manifest.json.template, scripts/tag-files.sh, tests/sanity/test/utils-scripts/test-component-utils.js
Part of fixes for https://github.com/zowe/zowe-install-packaging/issues/1769
- Automatically configure components if manifest has `apimlServices.static[].file` or `desktopIframePlugins[]` defined.
- With this changes, component no longer need to prepare static definition files themselves or run zowe-install-iframe-plugin.sh in configure.sh.
- After …
=> automatically configure components based on manifest definitions

Jenkinsfile, Jenkinsfile.nightly, Jenkinsfile.release, tests/installation/Jenkinsfile
Test network connection issues.
- Use new jenkins agent located in WDC06.
=> PR-1856 for rc

manifest.json.template
=> Bump overall version to 1.19

Jenkinsfile, Jenkinsfile.release, tests/sanity/.mocharc-docker.yml
This is identical to https://github.com/zowe/zowe-install-packaging/pull/1851 except pointing to RC. Please close one or the other if the duplication is not needed.
=> PR-1851 for RC

manifest.json.template
- Revert the partial upgrade of apiml to 1.19 until the issues with #1855 are resolved
=> Revert catalog to 1.18

Jenkinsfile, manifest.json.template, scripts/zowe-install-components.sh
Signed-off-by: at670475 <andrea.tabone@broadcom.com>
Fixes 
- 
---
---
---
---
=> Use new lite jars

tests/sanity/test/utils-scripts/test-component-utils.js
.only mark is left on test case.
- Remove .only and verify test result
=> remove .only

manifest.json.template
Part of #1866 
- update source dependencies to released version for app framework components
=> Revert app framework source to released version

manifest.json.template
=> Bump app-framework version to 1.19.0

manifest.json.template
Part of #1866 
- 1.18 license update
=> Bump license

tests/sanity/test/e2e/test-06-vt.js
- There have been some test case failures regarding the VT Terminal: **test VT Terminal - should launch app correctly**
- The goal of this PR is to fix the specified test case failure
=> Modified vt-terminal test cases

manifest.json.template
Part of #1866 
- Update source tag of zowe-install-packaging-tools
=> Update source tag

Jenkinsfile.release
Fixes missing line feed when run docker promotion.
- Add missing line feeds.
=> add missing \n to docker promote

manifest.json.template
=> RC build for 1.19

manifest.json.template, tests/sanity/test/apiml/test-api-zosmf-via-gateway.js, tests/sanity/test/cookie-helper.js, tests/sanity/test/zlux/test-zlux-server.js, tests/sanity/test/zlux/utils.js
Add support for new destination property to iframe pluginDefinition.json
Fixes 
- 
---
---
---
---
=> Double iframe src

Jenkinsfile.nightly, Jenkinsfile.release
Implements #1891 
- Add running and testing of the docker image to nightly
- Add links to docker image in promote steps
=> Add docker build to nightly and promote steps

manifest.json.template
=> James Struga Updated RC with new refactor code

manifest.json.template
Signed-off-by: jandadav <janda.david@gmail.com>
Fixes 
- 
---
---
---
---
=> bump staging to latest apiml snapshot

manifest.json.template, tests/sanity/test/zlux/test-zlux-server.js
Add support for new destination property to iframe pluginDefinition.json
Fixes 
- 
---
---
---
---
=> iframe updates uss mvs

tests/sanity/.mocharc-docker.yml
- cherry-pick changes from rc branch
=> exclude caching service and zss gateway tests

bin/utils/zowe-variable-utils.sh
Fixes potential issue when the instance.env doesn't have line feed at the end, some test cases may fail due to append variables to the variable at the end of instance.env.
- Verify if there is line feed at the end of instance.env, add one if it's not there.
=> fix potential issues when instance.env doesn't have line feed at the end

bin/zowe-configure-component.sh
Fixes #1899 
- Remove empty if block
=> Remove empty block

Jenkinsfile.nightly
Fixes #1900 
- Define missing variables upfront
=> Define missing variables upfront

Jenkinsfile.release
=> Fix formatting bug

manifest.json.template
=> Add zlux blocker

manifest.json.template
- Include updated versions of explorer ui components
- Bump APIML
=> Bump ui explorer version

playbooks/host_vars/vm30102.yml, playbooks/hosts
Signed-off-by: Raymond Li <raymondyanli@gmail.com>
Add a new system vm30102.svl.ibm.com for smu so that internal CICD can install the latest zowe on it.
Fixes 
- 
---
---
---
---
=> add a new system for smu

bin/zowe-support.sh
Attempt to fix #1920
- Update support script to use new utils lib script
=> Source the whole utils script

Jenkinsfile
- Switch pipeline admin from Steve to Tom
=> Remove Steve as admin and add Tom

manifest.json.template
=> update sourceDependencies tags

manifest.json.template
=> fix zss tag

manifest.json.template
=> Update staging version to 1.20.0

manifest.json.template
=> Updated web-ui to latest staging

tests/installation/Jenkinsfile
- [x ] Bugfix 
npm@7.5.2 requires node v10 and it's incompatible with node v8.17.0 we are using in build agent.
- remove npm upgrade
=> try without npm upgrade

Jenkinsfile.release
Fixes 
- adding error command to stop the build when smpe tar or zip is not found.
---
---
---
---
=> catch error on smpe tar or zip that does not exists

manifest.json.template
=> update with latest 1.19.1 license

scripts/utils/zowe-install-xmem.sh
Fixes #1952 
- This is not a full fix of issue described in #1952, but more for debug purpose to understand why this issue happens.
- Before copy parmlib member, check if it's exists
- If it's already existed, will try to delete it first
- If the data set is in-use, show who is using it.
=> delete parmlib before copying, if it's in-use, show who is using it

playbooks/roles/ptf/tasks/main.yml
Fixes issue when using current playbook to install old two PTFs.
- Properly check `ptfs_existence` after `is_ptf_installed`.
=> properly check ptf2 installation

scripts/zowe-install-zlux.sh
Fixes https://github.com/zowe/zlux/issues/596
Fixes https://github.com/zowe/zlux/issues/595
This PR works in cooperation with https://github.com/zowe/zlux-app-server/pull/144 and https://github.com/zowe/zss/pull/257 to unpackage the app-server and zss manifest files to the right locations at install time.
=> Add manifest files to appserver, zss

smpe/bld/ptf.readme.htm, smpe/bld/smpe-service.sh
Fixes 
- PR #1972 updated the generation of the PTF install instructions, but not all related changes were committed, resulting in a error when the JCL embedded in the instructions is used as-is. This PR adds the additional change needed. Now, if there is only 1 PTF, it will list 'none' in the …
=> split logic to populate list of coreq & coreq in JCL

smpe/bld/ptf.readme.htm
update internal build documentation
Fixes 
- update internal build documentation
---
---
---
--- …
=> update comments in ptf.readme.htm

bin/utils/common.sh, bin/zowe-install-component.sh, tests/sanity/test/utils-scripts/test-common.js
Fixes issue that ZWE_LOG_LEVEL_ config doesn't take effect.
- Fix usage of variable
- Add test cases
=> fix bug on log level

Jenkinsfile.nightly
Fixes issue that after regular nightly build test, there is no full functional running Zowe instance on marist.
- Move docker test to the first
=> move docker test as the first

Jenkinsfile.nightly
Fixes issue that if CLI bundle fails, nightly promoting pipeline will exit without slack message.
- Ignore CLI promotion errors, instead show warnings in slack message.
=> ignore cli promote failures

bin/internal/prepare-workspace.sh, bin/utils/component-utils.sh, bin/zowe-configure-component.sh, bin/zowe-configure-instance.sh
Temporary fix for #1980 
- Move manifest `appfwPlugins` handling to runtime
This is temporary fix, we may revert it in the future.
=> move appfwPlugins handling to runtime (temporary fix for #1980)

bin/zowe-install-component.sh
Fixes redundant space in shell var assignment
- Remove space
=> remove space for var assignment

manifest.json.template
=> RC Build for 1.20.0

dco_signoffs/Jadin Luong-zowe-install-packaging.txt
Added a sign off to a commit missing a DCO.
=> Added sign off for commit missing a DCO

manifest.json.template
=> Bump apiml 1.21 SNAPSHOT

Jenkinsfile
=> Fix hardcoded staging keyword for auto test

manifest.json.template
=> Updated zss with bug fix

manifest.json.template
=> Update apiml in rc to 1.20.14

manifest.json.template
=> Updated padding of token text

manifest.json.template
=> Update APIML 1.20.15

containers/server-bundle/run_inner.sh
- Small bugfix for manifest.yml and manifest.json not being read due to missing `$`
=> Small syntax bugfix for container

playbooks/group_vars/zoweNode.yml, playbooks/roles/configure/defaults/main.yml, playbooks/roles/configure/tasks/configure_instance.yml
Fixes z/osmf version checking is flaky in some cases that APIML_SECURITY_ZOSMF_JWT_AUTOCONFIGURATION_MODE auto mode is not working well.
- Allow to customize this option per host in ansible playbook.
=> allow to customize APIML_SECURITY_ZOSMF_JWT_AUTOCONFIGURATION_MODE

playbooks/group_vars/marist.yml, tests/sanity/test/apiml/test-caching-service-apis-via-gateway.js
fixes nightly build
contains auth changes from https://github.com/zowe/api-layer/issues/861
=> Update caching service tests for new auth

bin/utils/component-utils.sh
Fixes empty api static definition file generated in api-defs folder
- Display error message if `apimlServices.static[].file` is missing
- Display error message if `appfwPlugins[].path` is missing
=> check if file/path defined in manifest is accessible

manifest.json.template
=> Set AC, DS, GW, common to 1.20.18

playbooks/roles/zowe/tasks/uninstall_keyring_acf2.yml
Fixes occasionally delete certificate error.
- Do a full cleanup on the user keyring.
=> full clean up on keyring entries

manifest.json.template
=> fix for rc4

tests/sanity/test/apiml/test-authentication-zosmf-via-gateway.js, tests/sanity/test/apiml/test-caching-service-apis-via-gateway.js, tests/sanity/test/apiml/test-login-to-system-and-logout.js, tests/sanity/test/apiml/test-zss-via-gateway.js, tests/sanity/test/apiml/utils.js
Fixes #2036 
- Add debug code for troubleshooting
=> catch caching service request 400/500 exception

Jenkinsfile, tests/sanity/test/explorer-apis/test-api-datasets-v2.js
=> Improve dataset api test debug message

tests/sanity/test/apiml/utils.js
Fixes error of using JSON.stringify.
-
=> remove json stringify usage

bin/internal/prepare-environment.sh, playbooks/all_host_vars_list.yml, playbooks/roles/configure/defaults/main.yml, playbooks/roles/configure/tasks/configure_instance.yml, playbooks/roles/configure/tasks/main.yml, playbooks/roles/verify/defaults/main.yml, playbooks/roles/verify/tasks/main.yml, tests/sanity/test/apiml/test-caching-service-apis-via-gateway.js
- remove usage of `ZOWE_CACHING_SERVICE_START`
=> treat caching-service like other services

playbooks/install-ptf.yml, playbooks/roles/stop/tasks/main.yml, playbooks/roles/zos/files/kill-zombies.sh, playbooks/roles/zos/tasks/main.yml
Fixes zombies address spaces left.
- cancelling all address spaces from ZWESVUSR after zowe is stopped
=> kill all zombies!

bin/zowe-install-component.sh
- the zowe-install-component.sh script was not properly untarring tar files
- this PR contains the fixes to those issues
=> Fixed untar issue for zowe-install-component script

playbooks/roles/stop/tasks/main.yml, playbooks/roles/zowe/tasks/uninstall.yml
Fixes issue that kill-zombies script is not executed without using stop playbook.
- Call stop module during uninstall
=> call stop module in uninstall

playbooks/roles/configure/tasks/locate_xmem.yml, playbooks/roles/configure/tasks/locate_zowe_start.yml, playbooks/roles/configure/tasks/locate_zowe_stop.yml, playbooks/roles/configure/tasks/purge_job_outputs.yml, playbooks/roles/configure/tasks/show_logs.yml, playbooks/roles/start/tasks/main.yml, playbooks/roles/stop/tasks/main.yml
Fixes stop playbook may fail on missing zowe_xmem_stc_name or zowe_stop_path values.
- Add conditional check and make sure locate module not fail
=> validate existence of zowe_xmem_stc_name and zowe_stop_path

smpe/bld/service/current-hold-ACTION.txt
=> add hold data for new zowe-setup-certificate variable

scripts/instance.template.env, smpe/bld/service/current-hold-ACTION.txt
-  The param added here is used by zss to determine whether or not to use tls automatically. false will set it to the v1.20 and older behavior where tls is not used, but it defaults to true in order to automatically use tls. This has a code comment to explain why people would want to change this …
=> Add parameter to control zss tls for backward compat

manifest.json.template
=> RC build for Web-UI v1.21.0

manifest.json.template
=> Update API ML dependencies for release 1.21

manifest.json.template
=> update launcher to 0.0.3

bin/apiml_cm.sh, bin/zowe-setup-certificates.sh
Signed-off-by: achmelo <a.chmelo@gmail.com>
Part of fixes for https://github.com/zowe/api-layer/issues/1334
- Properly pass `VERIFY_CERTIFICATES` and `NONSTRICT_VERIFY_CERTIFICATES` to apiml_cm.sh
=> Fix warning message of IO error when exporting jwt secret

bin/apiml_cm.sh
=> remove exporting jwt secret step when using keyring

manifest.json.template
=> adding workaround for docker

playbooks/roles/start/defaults/main.yml, playbooks/roles/start/tasks/wait_for_zowe.yml
This PR adds tests to check status of ZSS.
- New test to check if zss up and running
- New test to check if the user can login to zss
=> Wait for being able to login to zss

bin/utils/common.sh, playbooks/all_host_vars_list.yml, playbooks/group_vars/marist.yml, playbooks/host_vars/marist-2.yml, playbooks/host_vars/marist-3.yml, playbooks/roles/configure/defaults/main.yml, playbooks/roles/configure/tasks/create_keyring.yml, playbooks/roles/verify/tasks/main.yml, scripts/instance.template.env, smpe/bld/service/current-hold-ACTION.txt, tests/installation/Jenkinsfile, tests/installation/src/__tests__/extended/certificates/external-certificate.ts, tests/installation/src/__tests__/extended/certificates/nonstrict-verify-certificates.ts, tests/installation/src/__tests__/extended/certificates/nonstrict-verify-external-certificate.ts, tests/installation/src/__tests__/extended/certificates/verify-certificates.ts, tests/installation/src/__tests__/extended/keyring.ts, tests/sanity/test/apiml/test-zss-routing.js
=> merge rc back to staging

playbooks/roles/start/defaults/main.yml, playbooks/roles/start/tasks/wait_for_zowe.yml
=> Revert PR-2096

bin/apiml_cm.sh, bin/internal/prepare-instance.sh
Fixes error "sed: Unknown command" when validating domain name.
- Fix sed command.
=> fix sed command when validating domain

manifest.json.template
=> Upgrade Zowe staging to 1.22.0

manifest.json.template
=> update Web-UI components

manifest.json.template
=> Update API ML to 1.22 version

.pax/pre-packaging.sh, scripts/zowe-install-MVS.sh
Fixes SMPE build failure
- Find correct zss pax file
=> find zss pax

Jenkinsfile.nightly
Fixes 
- Increase keyring test running frequency to Weds and Sats
---
---
---
---
=> increase keyring test run frequency to run it on Weds

Jenkinsfile, containers/server-bundle/Dockerfile, install/zowe-install.sh, manifest.json.template
Splits up docker ssh commands into smaller commands so when a failure occurs, we can see which part caused the failure.
Also, the manifest was pointing to PRs when it didnt need to, so reseting those to staging.
=> Splitting up docker build commands

bin/internal/prepare-instance.sh, bin/utils/zosmf-utils.sh, bin/zowe-setup-certificates-for-ha.env, bin/zowe-setup-keyring-certificates-for-ha.env
Fixes 
- zowe-setup-certificates-for-ha.env and zowe-setup-keyring-certificates-for-ha.env is missing definition of NONSTRICT_VERIFY_CERTIFICATES
- zosmf verification is using wrong curl option `--responseType`
- fix missing variables in global_validate function
- configure_components function should prepare .env directory instead of workspace
=> copy nonstrict to ha and few other fixes

playbooks/roles/configure/tasks/create_security_defn.yml, playbooks/roles/docker/tasks/configure-zowe-for-docker.yml
Fixes 
- Docker build requires APIML_SECURITY_AUTHORIZATION_ENDPOINT_URL to make gateway /services endpoint working
- ZWESECUR is not configured with correct security PRODUCT
=> add APIML_SECURITY_AUTHORIZATION_ENDPOINT_URL for docker configure

tests/sanity/.mocharc-docker.yml
=> Disable endpoint test on docker scenario

playbooks/roles/zowe/defaults/main.yml
Fixes keyring test failure of:
```
RACDCERT GENCERT ID(ZWESVUSR)   SUBJECTSDN( CN('Zowe Development Instances certificate') OU('API Mediation Layer') O('Zowe Sample
') L('Prague') SP('Prague') C('CZ'))  SIZE(2048) NOTAFTER(DATE(2030-05-01)) WITHLABEL('ZoweCert') KEYUSAGE(HANDSHAKE) ALTNAME(IP(148 …
```
=> more known cert to clean up

files/jcl/ZWEKRING.jcl, playbooks/all_host_vars_list.yml, playbooks/roles/configure/defaults/main.yml, playbooks/roles/configure/tasks/create_keyring.yml
Verified with https://wash.zowe.org:8443/job/zowe-install-test/job/users%252Fjack%252Fkeyring-fixes/3/console
=> keyring fixes

playbooks/host_vars/marist-1.yml, playbooks/host_vars/marist-3.yml, playbooks/roles/configure/tasks/main.yml
=> use non-default jwtsecret label to catch more issues

playbooks/roles/configure/tasks/main.yml, playbooks/roles/zowe/tasks/uninstall_keyring_acf2.yml, playbooks/roles/zowe/tasks/uninstall_keyring_racf.yml, playbooks/roles/zowe/tasks/uninstall_keyring_tss.yml
Test passed on:
- marist 1: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/job/users%252Fjack%252Fcopy-cert/1/
- marist 2: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/job/users%252Fjack%252Fcopy-cert/2/
=> fix copying cert issues

bin/instance/example-zowe.yaml, scripts/instance.template.env
=> change default ZWE_CACHING_SERVICE_PERSISTENT value to empty

manifest.json.template
=> Update explorer api versions

manifest.json.template
=> Web-UI build for 1.22.0

manifest.json.template
=> Use the released version of the API ML

tests/sanity/test/apiml/test-api-gateway-version.js
=> [For RC] Remove unused Gateway version test code

dco_signoffs/Pavel Jares-zowe-install-packaging.txt
=> Add DCO sign off for previous unsigned commits

playbooks/host_vars/marist-4.yml, playbooks/hosts
Part of https://github.com/zowe/zowe-install-packaging/issues/1397
=> add marist4

containers/server-bundle/build.sh
Signed-off-by: Adarshdeep Singh Cheema <adarshdeepsinghcheema@Adarshdeeps-MacBook-Pro.local>
Fixes 
- 
---
---
---
---
=> correcting the examples in the build.sh

bin/zowe-install-component.sh
N/A Tests for the changes have been added (for bug fixes / features)
N/A Necessary documentation (if appropriate) have been added / updated
✔️  DCO signoffs have been added to all commits, including this PR
✔️  Bugfix 
Fixes 
NODE_HOME missing message in install script, changed from warning to error so zowe install stops at failure
✔️  No
---
* Affected …
=> NODE_HOME warning to error so zowe install stops at failure

tests/installation/Jenkinsfile
=> Adding credentials to grab jenkins test report

scripts/zowe-install-MVS.sh
Reverts zowe/zowe-install-packaging#2211
=> Revert "Create dataset for ZIS plugins during installation procedure"

tests/sanity/.mocharc-docker.yml, tests/sanity/test/e2e/test-01-login.js, tests/sanity/test/e2e/utils.js
=> Disable ip exp docker

Jenkinsfile, tests/installation/Jenkinsfile
=> fix PR jenkins build icon

bin/internal/prepare-environment.sh
Fixes issues caused by ZWESVUSR home directory doesn't exist.
=> cd to a directory for sure exists

Jenkinsfile, Jenkinsfile.nightly, tests/installation/Jenkinsfile
=> Fix default CLI artifactory path

manifest.json.template
=> Rc build for 1.23.0

manifest.json.template
=> Add the version of API ML

manifest.json.template
=> Jobs and Data-sets version for RC

manifest.json.template
=> RC2 fix for logging token

.github/workflows/dummy.yml
A dummy workflow to enable repository manual triggering of Github Actions job.
=> dummy workflow

.github/workflows/base-images.yml, .github/workflows/base-jdk-images.yml, .github/workflows/base-node-image.yml
Rename to same workflow names will be used.
=> rename to target workflow name

.github/workflows/base-images.yml, .github/workflows/base-jdk-images.yml, .github/workflows/base-node-images.yml, containers/base-jdk/README.md, containers/base-jdk/ubi/amd64/Dockerfile, containers/base-jdk/ubi/s390x/Dockerfile, containers/base-jdk/ubuntu/amd64/Dockerfile, containers/base-jdk/ubuntu/s390x/Dockerfile, containers/base-node/README.md, containers/base-node/ubi/amd64/Dockerfile, containers/base-node/ubi/s390x/Dockerfile, containers/base-node/ubuntu/amd64/Dockerfile, containers/base-node/ubuntu/s390x/Dockerfile, containers/base/README.md, containers/base/ubi/amd64/Dockerfile, containers/base/ubi/s390x/Dockerfile, containers/base/ubuntu/amd64/Dockerfile, containers/base/ubuntu/s390x/Dockerfile
Fixes #2238 
- Create base images.
=> Component base images

manifest.json.template
=> Upgrade Zowe version to 1.24

manifest.json.template
=> Update app-server components

manifest.json.template
Signed-off-by: achmelo <a.chmelo@gmail.com>
Fixes 
- 
---
---
Include SNAPSHOT version 1.24.2 for nightly builds
---
---
=> chore: udpate snapshot version

bin/zowe-configure-instance.sh, install/zowe-install.sh, scripts/zowe-create-ZIS-ds.sh
Signed-off-by: Timothy Gerstel <tgerstel@rocketsoftware.com>
Fixes https://github.com/zowe/zlux/issues/684
- Move ZIS dataset creation logic into separate script, invoke during configure time
---
---
* Description: Create dataset for ZIS plugins if such flags are specified during instance configuration *
---
* …
=> Move creation of ZIS plugin dataset to configure time

bin/instance/utils/zowe-configure-component.sh, bin/instance/utils/zowe-install-component.sh
Fixes script errors when run `<instance-dir>/bin/utils/zowe-install-component.sh`.
- Execute directly instead of sourcing script.
=> run script directly instead of source

bin/utils/node-utils.sh
=> exclude v14.17.2, fixes #2291

CHANGELOG.md, bin/zowe-configure-instance.sh, scripts/instance.template.env
- Add parameter for recording zis pluginlib in instance.env
- Add automation for recording zis pluginlib in instance.env if parameter is not provided
- Prefixed existing zis parameters in the instance creation script with zis_ for disambiguation
- Update changelog about all of these zis parameter …
=> Record pluginlib in instance

manifest.json.template
=> Upgrade version for jobs/data-sets apis

manifest.json.template
=> 1.24.0 app-server 

manifest.json.template
=> Update manifest explorer projects artifactory pattern

manifest.json.template
=> Roll back explorer-uss 

tests/installation/Jenkinsfile
=> Change default client node version

manifest.json.template
=> RC3 updates for CLI

manifest.json.template
=> Bump Zowe version to 1.25.0

manifest.json.template
=> Updated WebUI component to 1.25.0

manifest.json.template
=> Update version of the API ML components to 1.25

zowe_pswi_tech_prev.md
Adds a md file describing the Zowe PSWI.
Fixes #1174 
- This PR adds a short description file for a new Zowe PSWI as a technology preview. In the future, as the Zowe PSWI becomes a GA, this file could be removed, because the full documentation will be prepared.
No
No
Signed-off-by: jp669844 <jan.prihoda@broadcom.com>
=> A simple Zowe Portable Software Instance description file

bin/utils/node-utils.sh, tests/installation/Jenkinsfile, tests/sanity/test/utils-scripts/test-node-utils.js
=> fixes #2364 deprecating node v8

bin/instance/utils/convert-for-k8s.sh, bin/internal/prepare-environment.sh, containers/kubernetes/README.md
Fixes explorer apps failure if accessing from 8544 port.
- introduce ZWE_EXTERNAL_PORT and default to GATEWAY_PORT
=> introduce ZWE_EXTERNAL_PORT and default to GATEWAY_PORT

containers/zowe-launch-scripts/prepare.sh
Fixes failures if utility_tools is on static version when preparing zowe-launch-scripts image.
=> fix failures on parsing manifest version

manifest.json.template
=> bump version to 1.26

.github/workflows/build-packaging.yml
=> A dummy workflow file to make manual inputs available on all branches

manifest.json.template
=> upgrade components to 1.26

manifest.json.template
=> Use the current versions

.github/workflows/cicd-test.yml
=> add dummy workflow file for cicd test

.pax/prepare-workspace.sh, Jenkinsfile, README.md, files/zlux/config/plugins/org.zowe.zosmf.workflows.json, manifest.json.template, tests/sanity/test/e2e/test-11-workflows.js, tests/sanity/test/e2e/utils.js
Signed-off-by: Aditya Ranshinge <aranshinge@rocketsoftware.com>
Removed zosm-auth, zss-auth and zlux-workflow as default plugin
---
---
---
---
=> Removed zosm-auth, zss-auth and zlux-workflow as default plugin

files/zlux/config/plugins/org.zowe.zlux.sample.angular.json, files/zlux/config/plugins/org.zowe.zlux.sample.iframe.json, files/zlux/config/plugins/org.zowe.zlux.sample.react.json, tests/sanity/test/e2e/test-07-iframe.js, tests/sanity/test/e2e/test-12-angular-sample.js, tests/sanity/test/e2e/test-13-react-sample.js, tests/sanity/test/e2e/test-14-ip-explorer.js, tests/sanity/test/e2e/utils.js
Signed-off-by: Aditya Ranshinge <aranshinge@rocketsoftware.com>
Removed sample app plugin json
---
---
---
---
=> Removed sample app plugin json

containers/build/parse-manifest-to-deployment.sh, containers/kubernetes/samples/sample-deployment.yaml, containers/kubernetes/workloads/instance-env/api-catalog-deployment.yaml, containers/kubernetes/workloads/instance-env/app-server-deployment.yaml, containers/kubernetes/workloads/instance-env/caching-deployment.yaml, containers/kubernetes/workloads/instance-env/discovery-statefulset.yaml, containers/kubernetes/workloads/instance-env/explorer-ip-job.yaml, containers/kubernetes/workloads/instance-env/explorer-jes-deployment.yaml, containers/kubernetes/workloads/instance-env/explorer-mvs-deployment.yaml, containers/kubernetes/workloads/instance-env/explorer-uss-deployment.yaml, containers/kubernetes/workloads/instance-env/files-api-deployment.yaml, containers/kubernetes/workloads/instance-env/gateway-deployment.yaml, containers/kubernetes/workloads/instance-env/jobs-api-deployment.yaml, containers/kubernetes/workloads/zowe-yaml/api-catalog-deployment.yaml, containers/kubernetes/workloads/zowe-yaml/app-server-deployment.yaml, containers/kubernetes/workloads/zowe-yaml/caching-deployment.yaml, containers/kubernetes/workloads/zowe-yaml/discovery-statefulset.yaml, containers/kubernetes/workloads/zowe-yaml/explorer-ip-job.yaml, containers/kubernetes/workloads/zowe-yaml/explorer-jes-deployment.yaml, containers/kubernetes/workloads/zowe-yaml/explorer-mvs-deployment.yaml, containers/kubernetes/workloads/zowe-yaml/explorer-uss-deployment.yaml, containers/kubernetes/workloads/zowe-yaml/files-api-deployment.yaml, containers/kubernetes/workloads/zowe-yaml/gateway-deployment.yaml, containers/kubernetes/workloads/zowe-yaml/jobs-api-deployment.yaml, manifest.json.template
Use `1-ubuntu` image tags instead of `latest-ubuntu`.
=> pull v1 image for v1

manifest.json.template
=> add missing job as kind for explorer-ip

Jenkinsfile, manifest.json.template
=> Add metrics service

manifest.json.template
=> add explorer-ip as new imageDependencies

dco_signoffs/Jack Jia-zowe-install-packaging.txt, manifest.json.template
=> bump apiml minor version

Jenkinsfile, manifest.json.template
=> Add metrics service to nightly

.github/workflows/build-packaging.yml
=> Adding metrics service into core components

manifest.json.template
=> fix branch build of explorer api/ui

.pax/post-packaging.sh, playbooks/group_vars/marist.yml
=> Change from VOL ZOWE02 to ZOWE03

manifest.json.template
=> Update apiml for rc

manifest.json.template
=> Updated build for 1.26 RC

playbooks/group_vars/marist.yml, playbooks/host_vars/marist-4.yml
=> ZOWE03 is only for marist 4

bin/internal/prepare-environment.sh, install/zowe-install.sh
=> Fix: install metrics service and run with GW group

bin/internal/prepare-environment.sh, install/zowe-install.sh
=> Add metrics service install and start

.github/workflows/cicd-test-readme.md, .github/workflows/cicd-test.yml, tests/installation/src/__tests__/basic/install-api-gen.ts, tests/installation/src/__tests__/basic/install-ext.ts, tests/installation/src/merge-test-reports.ts, tests/installation/src/utils.ts
=> cicd test improvements

tests/sanity/test/utils-scripts/test-node-utils.js
(current year -gt 2021)
Signed-off-by: achmelo <a.chmelo@gmail.com>
Fixes 
- Node utils is providing different warning messages for node v8.17 because of the new year
elif [[ ${node_major_version} -eq 8 ]] && [[ ${current_year} -gt 2021 ]]
---
---
---
* Part: _name of …
=> node-utils consider node v8 as no longer supported

manifest.json.template
=> upgrade desktop components

playbooks/roles/kubernetes/tasks/deploy-zowe-k8.yaml
Signed-off-by: Adarshdeep Cheema <adarshdeep.cheema@ibm.com>
Fixes 
- 
---
---
---
---
=> correcting the option to use the password when doing sshpass

.github/workflows/build-packaging.yml, .github/workflows/cicd-test.yml, tests/installation/src/__tests__/extended/node-versions/node-v16.ts
=> Add node v16 support in server test

manifest.json.template
=> RC1 for app server

manifest.json.template
=> RC 1 for explorer APIs

manifest.json.template
Signed-off-by: Adarshdeep Cheema <adarshdeep.cheema@ibm.com>
Fixes 
- 
---
---
---
---
=> updating the explorer-jes version

manifest.json.template
=> Update APIML binaries for RC 1

Jenkinsfile, manifest.json.template
=> Fix missing versions and extension for RC

manifest.json.template
=> Update image dependencies for apiml RC 1

manifest.json.template
=> Bump apiml binaries

manifest.json.template
=> Bump apiml image versions

bin/libs/component.sh
=> verify if extension exists before finding it's sub-directories

dco_signoffs/Adarsh-Cheema-zowe-install-packaging.txt
Signed-off-by: Adarshdeep Cheema <adarshdeep.cheema@ibm.com>
Fixes 
- 
---
---
---
---
=> updating the dco signoffs

smpe/bld/SMPMCS.txt, smpe/bld/_README.txt, smpe/bld/smpe-fmid.sh
Signed-off-by: Onno Van den Troost <onno@us.ibm.com>
SMP/E build verifies that all files are copied to the RELFILEs
Fixes #2590
- SMP/E build verifies that all files are copied to the RELFILEs
- add documentation on how to add/remove SMP/E metadata
---
---
---
* Part: …
=> relfile content validation

manifest.json.template
Updates manifest to point apps at the builds being generated from v2.
=> Update apps manifest to v2

.pax/pre-packaging.sh, ZOWE.md, bin/commands/.examples, bin/commands/certificate/pkcs12/create/ca/.parameters, bin/commands/certificate/pkcs12/create/ca/index.sh, bin/commands/certificate/pkcs12/create/cert/.parameters, bin/commands/certificate/pkcs12/create/cert/index.sh, bin/commands/init/.examples, bin/commands/init/.parameters, bin/commands/init/certificate/.parameters, bin/commands/init/mvs/.errors, bin/commands/init/mvs/.help, bin/commands/init/mvs/.parameters, bin/commands/init/mvs/index.sh, bin/commands/init/security/index.sh, bin/commands/init/stc/.errors, bin/commands/init/stc/.parameters, bin/commands/init/stc/index.sh, bin/commands/init/vsam/.errors, bin/commands/init/vsam/.parameters, bin/commands/init/vsam/index.sh, bin/commands/install/.errors, bin/commands/install/.parameters, bin/commands/install/index.sh, bin/libs/certificate.sh, manifest.json.template
Signed-off-by: Leanid Astrakou <lastrakou@rocketsoftware.com>
Addresses partially https://github.com/zowe/zowe-install-packaging/issues/2630 + Jenkins pipeline build (thank you to Jack)
TODO: Future version support to check for an upgrade
- Change allow-overwritten to allow-overwrite (because it overwrites rather than accepts with no changes)
- Modify …
=> --overwritten changes + fix Jenkins automation

manifest.json.template
=> launcher PR30 merged, use snapshot builds

manifest.json.template
=> 1.27.2 update cli packages and plugins versions

.dependency/zwe_doc_generation/index.js, .dependency/zwe_doc_generation/md-content.js
Linked to #2460 
- 
---
---
---
---
=> Fix documentation generation for zwe cli

.github/workflows/zwe-doc-generation.yml
=> Add dummy workflow file for zwe doc gha

playbooks/roles/zos/files/show_job_log.rexx, playbooks/roles/zos/files/show_job_log_with_ddname.rexx
show_job_log.rexx sometimes fail on z/OS v2.5 with error:
```
IRX0250E System abend code 0C4, reason code 00000017.   
IRX0255E Abend in host command ISFACT or address environment routine SDSF.    
54 *-*  Address SDSF "ISFACT ST TOKEN('"TOKEN.ix"') PARM(NP ?)" ,        "( prefix jds_" 
+++ RC(-196) +++ …
```
=> temporary fix to remove call of ISFACT for v2.5

Jenkinsfile.nightly
=> disable nightly auto trigger

.github/workflows/build-packaging.yml, Jenkinsfile, manifest.json.template
=> Fix APIML snapshots path

manifest.json.template
=> upgrade zowe to version 1.28.0

.github/workflows/build-packaging.yml
=> GHA with PSWI for v1

.github/workflows/build-packaging.yml
=> Add PSWI for v2 build pipeline

manifest.json.template
=> excludePatterns is deprecated, v2 pipeline

.github/workflows/build-packaging.yml, manifest.json.template
=> excludePatterns is deprecated, v1 changes

smpe/bld/SMPMCS.txt, smpe/bld/_README.txt, smpe/bld/smpe-fmid.sh
Signed-off-by: Onno Van den Troost <onno@us.ibm.com>
SMP/E build verifies that all files are copied to the RELFILEs
Fixes #2590
fixed in v2 with #2612
- SMP/E build verifies that all files are copied to the RELFILEs
- add documentation on how to add/remove SMP/E metadata
---
---
* Description: _1 line …
=> v1 relfile content validation

.github/workflows/snyk-analysis.yml, .github/workflows/snyk-kubernetes.yml
=> disable auto scan on every commits

bin/libs/zos-jes.sh
Fixes infinite waiting for job complete code with JES3.
- Identify JES3 and exit right away
=> Allow wait_for_job to work on JES3

manifest.json.template
Fixes #2702 
This should extract and install apiml-sample-extension into `<runtime>/components` directory instead of leaving the zip file under `<runtime>/files` directory.
- Install apiml-sample-extension when packaging Zowe.
- This component is not listed in `example-zowe.yaml` for now. Please let me …
=> install apiml-sample-extension to runtime components directory

.github/workflows/cicd-test.yml
=> upload test reports for v2

.github/workflows/cicd-test.yml
=> zip test reports and upload

manifest.json.template
Fixes 
Update artifact IDs for Jobs and Files APIs.
Files: https://zowe.jfrog.io/artifactory/libs-snapshot-local/org/zowe/explorer/files/files-api-package
Jobs: https://zowe.jfrog.io/artifactory/libs-snapshot-local/org/zowe/explorer/jobs/jobs-api-package/1.0.16-SNAPSHOT/
---
* Affected function: _general area …
=> Use new explorer API artifacts

manifest.json.template, playbooks/group_vars/marist.yml
=> Update jobs and files api artifacts

manifest.json.template
Signed-off-by: Tom Zhang <t.yczhang@ibm.com>
Fixes 
- 
---
---
---
---
=> Change in source Dependencies tags for v2

playbooks/group_vars/marist.yml, playbooks/roles/fmid/defaults/main.yml, playbooks/roles/zowe/defaults/main.yml, playbooks/roles/zowe/tasks/uninstall.yml
=> cleanup possible v2 datasets for v1
