scripts/zowe-init.sh

rtc defect 21266: remove existing environment entries before adding new

---

artifactory-download-spec.json
scripts/zowe-api-mediation-configure.sh

This PR includes latest APIML build.
It fixes the substitution of new `STATIC_DEF_CONFIG` variable.
The PAX file will be used for testing of the APIML in PAX file.
We are researching a way how to select the latest version automatically.

WIP - Include latest APIML build

---

Jenkinsfile
artifactory-download-spec.json.template
install/zowe-install.sh
install/zowe-install.yaml.template
manifest.json
scripts/zowe-install-iframe-plugin.sh
scripts/zowe-parse-yaml.sh

Original issue https://github.com/zowe/zowe-install-packaging/issues/122
**Summary:** 
`manifest.json` is created to store Zowe version.
- This file will be added into PAX file under `zowe-{version}` folder, one level above `install`, `scripts` folders.
- During installation, this file will copied to target installation root folder.
- Installation script will pick version number from this file.
**Build & Test Result:**
Successful build https://wash.zowe.org:8443/job/zowe-install-packaging/job/issue-122-version/2/ are put in artifactory `libs-snapshot-local/com/project/zowe/0.9.3-ISSUE-122-VERSION/zowe-0.9.3-20181112.180848-2.pax`.
Build test result is https://wash.zowe.org:8443/job/zowe-install-test/job/094-fixes/3/console. Note: the failure test cases are caused by failing to start …

Issue 122 version

---

artifactory-download-spec.json.template

Contains the APIML build that fixes https://github.com/zowe/api-layer/issues/139.
It stops selecting the latest master of APIML automatically.

Select stable version of APIML

---

scripts/zowe-verify-post-install.sh

The check for the ICSF service is redundant because the ICSF job is checked earlier.  So is the CSF job, but the removed ICSF service check does not check CSF, so it's wrong.

Remove ICSF service check

---

artifactory-download-spec.json.template

This PR updates the APIML. It contains the fix to API catalog be accessed via `localhost` hostname.
All the APIML services are now listening on all interfaces

Update with latest APIML master

---

scripts/zowe-verify-post-install.sh

Check for non-discovery of port in runtime config files.
Print specific port name in error when checking ports in runtime config files.

Clarify port checking msgs

---

install/zowe-install.sh
scripts/zlux-install-script.sh
scripts/zowe-runtime-authorize.sh

Signed-off-by: Joe-Winchester <winchest@uk.ibm.com> 
The install log now has the folder creation all finished before it configures the certificates which makes for a cleaner install.
Zowe 0.9.5 runtime install completed into directory /u/winchj/zowe/0.9.5_a
The install script zowe-install.sh does not need to be re-run as it completed successfully
Setting up Zowe API Mediation Layer certificates...
ls: FSUM6785 File or directory "keystore/local_ca/extca.*.cer" is not found
keytool: trust_zosmf 4: scripts/apiml_cm.sh 436: FSUM9209 cannot execute: reason code = 0b1b03d1: EDC5139I Operation not permitted.
apiml_cm.sh --action trust-zosmf has failed. See /u/winchj/zowe-0.9.5/install/..//log/2018-12-17-19-33-49.log for more details
ERROR: z/OSMF is not trusted by the API Mediation Layer. Follow …

Cert Creation to lower in install sequence

---

install/zowe-check-prereqs.sh

Make the opercmd script executable, as it may not be set to executable by the current install, and it is required by the pre-install verify script.

Make opercmd executable

---

install/zowe-check-prereqs.sh

Check that there will be enough disk space to install Zowe before the install shell script is run.  The YAML file defines this target directory, which may or may not exist.  The zowe-check-prereqs.sh script uses the specified target, and checks its parent directory if the nominated one does not yet exist.

Check free space

---

scripts/zowe-install-iframe-plugin.sh

https://github.com/zowe/zlux-proxy-server/pull/41 will be enforcing plugins conformance to a spec (it'll evolve over time) and so this PR updates the iframe plugin creator to conform to the initial spec (apiVersion=1.0.0).

Made iframe plugin install use semver

---

install/zowe-install.sh
scripts/run-zowe.sh
scripts/zlux-install-script.sh
scripts/zowe-install-iframe-plugin.sh
scripts/zowe-prepare-runtime.sh
scripts/zowe-runtime-authorize.sh
scripts/zowe-verify.sh
scripts/zowe-zlux-configure-certificates.sh
scripts/zowe-zlux-configure-ports.sh
tests/test_zowe-zlux-configure-certificates.py

Depends on zlux repo also being updated, so please don't merge if you approve... I'll coordinate merging.
Text replace of zlux-example-server to zlux-app-server, zlux-proxy-server to zlux-server-framework

Fix zlux paths upon server rename

---

artifactory-download-spec.json.template
install/zowe-install.yaml.template
scripts/zowe-parse-yaml.sh
scripts/zowe-verify.sh
scripts/zowe-zlux-configure-ports.sh
tests/data/zluxserver.json

Update zLUX to 1.0.0+<Metadata>.
Include fixes removing the zLUX HTTP port, only HTTPS configured @ install time.

Update zLUX version

---

scripts/zowe-api-mediation-configure.sh

It includes `apiml_cm.sh` and all new scripts in `api-mediation/scripts` directory
Resolves #257

Make all APIML scripts executable

---

artifactory-download-spec.json.template

Explorer API release pipelines:
- https://wash.zowe.org:8443/job/Explorer-Data%20Sets-Release/
- https://wash.zowe.org:8443/job/Explorer-Jobs-Release/
are on place.
Do a PATCH_RELEASE after each change. The release pipeline will do tag and bump on master branch.

update download spec to use explorer api release pipeline results

---

scripts/zss/zowe-xmem-apf.sh
scripts/zss/zowe-xmem-check-if-sms.sh

* Get SMS information from DSCB1 and use a different command to APF-authorize if the data set is not SMS-managed
* Add comments about the DSCB1 used in the PDSE and SMS scripts

Use the volume parameter when APF-authorizing a non-SMS dataset

---

scripts/run-zowe.sh

Zowe STC starts nodeServer.sh using absolute path which causes logging issues

Fix missing node server log issue

---

scripts/zowe-copy-proc.sh

References to `opercmd` are changed to pre-pend them with `./` to allow for cases where CWD is not in the installing user's $PATH.

copyproc.sh should allow for no dot in $PATH

---

install/zowe-check-prereqs.sh
scripts/zowe-verify.sh

The part of `zowe-verify.sh ` that checks node.js version did not detect if node was not found, and neither did it check the version was at least the level required.  
`zowe-check-prereqs.sh` does check the version was at least the level required, but users might not run that.

verify node.js version in post-install script

---

files/templates/ZOWESVR.jcl

There was a typo in line 15 of the PROC.  It was a comment line but I fixed it anyway.

fix typo in ZOWESVR.jcl

---

scripts/zss/ocopyshr.rexx
scripts/zss/zowe-xmem-deploy-loadmodule.sh
scripts/zss/zowe-xmem-deploy-parmlib.sh
scripts/zss/zowe-xmem-deploy-proclib.sh

https://github.com/zowe/zowe-install-packaging/issues/384
`zowe-install-apf-server.sh` may fail to copy files to datasets, because the `cp` command can't write to a z/OS dataset if any process has it allocated even if only for READ
`scripts/zowe-copy-proc.sh` can't be re-used for xmem installation:
- we need to deploy PARMLIB, LOADLIB and PROCLIB not only PROCLIB
- the existing script works in TEXT mode only
- it expects a certain context (variables and temp datasets) set up in `zowe-install.sh`

Use ocopy shr to deploy xmem to datasets

---

scripts/zss/zowe-xmem-deploy-loadmodule.sh

The OCOPY documentation states that it cannot be used to copy
executables to an MVS dataset:
An executable file copied from the file system into an MVS
data set is not executable under MVS. Some required
directory information is lost during the copy.
Fixes #400

Use cp to copy ZWESIS01.

---

dco_signoffs/Matt Hogstrom-zowe-install-packaging.txt

Signed-off-by: Matt Hogstrom <matt@hogstrom.org>

Added signoffs for commits without a DCO for Hogstrom

---

scripts/zowe-init.sh

The `sed` string at line 316 incorrectly allowed trailing characters (in this case one blank) to be included as part of the value of ZOWE_IPADDRESS.  This fix excludes any trailing characters.

No trailing blank ip

---

artifactory-download-spec.json.template

I saw zlux had been upgraded to 1.2.0, adjust to pick up new versions.
Please double check some components doesn't have 1.2.0-STAGING, but have 1.2.0-RC instead.
Thanks.

include upgraded zlux components into staging

---

install/zowe-upgrade.sh

Signed-off-by: Vitek Vlcek <vitezslavvit.vlcek@ca.com>
Igor is working on official documentation in a separate PR.
Zowe short-term upgrade solution 
1. Zowe properly installed
2. downloaded PAX file of new version from https://zowe.org/download/ to `.../zowe/paxes` (eg `/a/zowe/paxes`)
1. stop Zowe instance if running
1. navigate to a directory for unpax typicaly this is in `.../zowe/builds` folder
2. unpax new Zowe version
* `pax -ppx -rf <path/to/pax>`   eg (`pax -ppx -rf /a/zowe/paxes/zowe-1.3.0.pax`)
3. run upgrade script
* `zowe-upgrade.sh <path/to/zowe/install> <path/to/unpaxed/new-zowe> <LOADLIB.DS.NAME> <path/to/backup>`
eg `zowe-upgrade..sh /a/zowe/1.2.0 /a/zowe/builds/zowe-1.3.0 ZWES.SISLOAD /a/zowe/backup`
* <path/to/zowe/install> - path to a Zowe install directory which you …

zowe upgrade script from 1.2.0 to 1.3.0

---

install/zowe-install.sh
install/zowe-install.yaml.template
scripts/zowe-support.sh

Rework of #508 &mdash; Change branch `master` &rarr; `staging`
Automatically collect basic data for support:
- Installation logs
- Scripts that are called from `run-zowe.sh`
- SW version:
- `manifest.json` file
- z/OS version
- Zava version
- NodeJS version
- Log files
- Started task output
- Process list
Also fixed bug in `zowe-install.yaml.template`: rename `zosmfUser` to `zosmfUserid`.

Add support script

---

install/zowe-install.sh
scripts/zowe-api-mediation-configure.sh
scripts/zowe-explorer-api-configure.sh

If the user enters blanks in the input string for any of the env variables, some of the `sed` commands fail because the way the `sed` string is quoted induces a syntax error if the variable has embedded blanks.  The `sed` strings have been re-formed to eliminate the syntax errors.

Sed blanks

---

scripts/configure/zowe-configure.sh

when  `$CONFIG_DIR/` is missing in ` . zowe-install-existing-plugin.sh $ZOWE_ROOT_DIR "org.zowe.zlux.auth.apiml" $ZOWE_ROOT_DIR/api-mediation/apiml-auth` in `zowe-install-existing-plugin.sh`
Error message:
`/a/vlcvi01/zowe/upgradable/scripts/configure/zowe-configure.sh: line 45: zowe-install-existing-plugin.sh: EDC5129I No such file or directory. (errno2=0x05620062)`

missing `$CONFIG_DIR/`

---

scripts/configure/zowe-configure-scripts.sh
scripts/zowe-start.template.sh
scripts/zowe-stop.template.sh

Fixes #560 by setting JOBNAME in `zowe-start.sh`.

Set jobname on ZOWESVR parent STCs

---

scripts/configure/zowe-copy-proc.sh
scripts/zowe-init.sh

fixed two problems:
* missing `ping`  - if `ping` is missing use `oping`
*  fixed problem `./ocopyshr.sh: /a/vlcvi01/zowe/upgradable/scripts/configure/zowe-copy-proc.sh 170: FSUM7351 not found`
Signed-off-by: Vitek Vlcek <vitezslav@vvvlcek.info>

fixed missing oping and ocopyshr.sh

---

scripts/configure/zowe-configure-api-mediation.sh
scripts/configure/zowe-configure-explorer-api.sh
scripts/zowe-init.sh

This is a fix for  https://github.com/zowe/zowe-install-packaging/issues/427, when z/OSMF runs on another host than whole zowe (APIML, Explorer APIs, ZAF), user performing installation has to carry out some post installation changes.
This PR introduces a new environment variable `ZOWE_ZOSMF_HOST` that is used like `ZOWE_ZOSMF_PORT`. 
To exploit it execute
```sh
export ZOWE_ZOSMF_HOST=myzosfm.customhostname.abc
export ZOWE_ZOSMF_PORT=1443
zowe-install.sh
```
if `ZOWE_ZOSMF_HOST` is not specified it defaults to `ZOWE_EXPLORER_HOST`.
`ZOWE_ZOSMF_HOST` is used in these places:
*   `scripts/configure/zowe-configure-api-mediation.sh`
from `https://$ZOWE_EXPLORER_HOST:$ZOWE_ZOSMF_PORT/zosmf/` 
to `https://$ZOWE_ZOSMF_HOST:$ZOWE_ZOSMF_PORT/zosmf/`
* …

Zosmf overide

---

scripts/configure/zowe-configure-zlux-certificates.sh
scripts/configure/zowe-configure.sh

When `externalCertificateAuthorities` in `zowe-install.yaml` is specified, value is not propagated to `zluxserver.json`
I had to delayed a deployment operation of zlux in `zowe-configure.sh`  so the certificates converted by mediation layer script are delivered to proper place so `zowe-configure-zlux-certificates.sh` can incorporate it into  `zluxserver.json`.

Ext cert auth

---

scripts/run-zowe.template.sh

Apply same update of https://github.com/zowe/zowe-install-packaging/pull/819 on staging.

Added export __UNTAGGED_READ_MODE=v6 to Zowe startup

---

scripts/tag-files.sh

Accommodates https://github.com/ibmruntimes/node/issues/142
This is a script that can be used in packaging pipelines to tag files. This script assumes the files came from a linux/windows machine in that it assumes files that are ASCII do not need to be converted to ASCII, just tagged. 
The exception is scripts in order to not break current use of shell invocation.
It's also recommended that JSON or YAML files that SED is used are set to 1047, so that the use of sed does not break. That is not covered in this script, as the files that sed is used on are not ALL JSON /YAML, but just a few.
The script does not break anything, but …

Script to tag files by extension

---

scripts/utils/validate-directory-is-writable.sh

no
---
---
* Description: fix for validate-directory-is-writable.sh: line 16: .: .: is a directory *
---
---
PR fixes this error message
```
/root/zowe/1.7.0/scripts/utils/validate-directory-is-writable.sh: line 16: .: .: is a directory
```

incorrect "."

---

bin/zowe-configure-instance.sh

Fixes https://github.com/zowe/zlux/issues/362
`install-app.sh` Can be used where it lives in the app-server code, but it needs environment variables or extra parameters to work properly there. Instead, `install-app.sh` is meant to exist in the instance directory so it can read the instance files to find where plugins should be placed. So, when an instance is created it should be copied into the bin folder for ease of use.

Copy install app on instance creation

---

bin/apiml_cm.sh
install/zowe-check-prereqs.sh
scripts/utils/zowe-copy-to-JES.sh
scripts/zowe-verify.sh

Fixes #799 
- Added TEMP_DIR variable in scripts to use instead of /tmp.
- TEMP_DIR variable is derived from TMPDIR USS variable or by default, /tmp.
It changes the temp directory used by the following scripts:
- apiml_cm.sh
- zowe-verify.sh
- zowe-check-prereqs.sh
- zowe-copy-to-JES.sh
---
**Affected function: _general area of interest_**
- Install and …

Remove hardcoded /tmp use from scripts

---

install/zowe-install.sh

Fixes #752 
Move the install_log file into the temp directory and if the install_directory is not writeable relocate our temp file to ${TMPDIR:-/tmp}

Move log into temp and relocate if r/o

---

bin/utils/zowe-install-iframe-plugin.sh

There are several lines show in `STDERR` log:
```
chtag: FSUM6180 file "/web/index.html": EDC5129I No such file or directory. (errno2=0x0594003D)
chtag: FSUM6180 file "/pluginDefinition.json": EDC5129I No such file or directory. (errno2=0x053B006C)
chtag: FSUM6180 file "/web/index.html": EDC5129I No such …
```

fix variable name in zowe-install-iframe-plugin.sh

---

bin/apiml_cm.sh

Openssl dependency removed; java replaced with "keytool -printcert " to get zosmf certificates.
Resolves issues:
https://github.com/zowe/zowe-install-packaging/issues/1129
https://github.com/zowe/zowe-install-packaging/issues/1130
https://github.com/zowe/zowe-install-packaging/issues/1131

Remove dependency on openssl & Replace java program to get zosmf certs

---

bin/internal/run-zowe.sh

Fixes the case in which you take a 1.8 instance and try to point it to a 1.9 install: 1.9 puts read-instance.sh in a new location and therefore we must check for both locations in case an upgrade is being attempted.

Backwards compatible path for read-instance.sh

---

files/zlux/config/plugins/org.zowe.zlux.proxy.zosmf.json

Remove proxy from default as it requires configuration and is made redundant by apiml & apiml-auth.
Why do this? Because https://github.com/zowe/zlux/issues/398
It was missed that the zosmf-auth repo comprised 2 plugins: the auth and the proxy. The proxy was the one generating the "needs configuration" warning, so it should be removed but was missed.

Remove a plugin from default config

---

Jenkinsfile.nightly

The nightly build had been failing for 3 days in a row. The failure is caused by network issue, at the stage of uploading raw contents to z/OS and packaging.
It looks not too bad during the day.
This PR moves the schedule 2 hours earlier and see if we can avoid the network failure.

move 2 hours earlier

---

Jenkinsfile.nightly

Try to avoid network failure for nightly build.

move nightly build to 2am

---

scripts/utils/zowe-install-proc.sh
scripts/utils/zowe-install-xmem.sh

Fixes #1284 
- update zowe-install-proc and zowe-install-xmem so that they reflect whether the internal call to copy-to-jes failed

zip 1284 - Make dataset scripts listen to rc of called script

---

files/zlux/config/plugins/org.zowe.zlux.auth.trivial.json
files/zlux/config/plugins/org.zowe.zlux.proxy.zosmf.json
files/zlux/config/plugins/org.zowe.zosmf.workflows.json
files/zlux/config/zluxserver.json

Part of this was done in rc branch for v1.10 but did not end up in staging.
Now in staging, the app server will load security plugins even if they are not found in server.json. They only need to be specified in the plugins folder in the same way apps are. So, I'm commenting out the zosmf object and changing the setting to not make zosmf plugin included by default, as it was not used by default in the past and recent changes may have unintentionally included it. This should fix it.

Trim list of auth plugins to just use zss, apiml(which includes zosmf)

---

manifest.json.template

Prepare for v1.12.0 release on staging branch. We can release hotfix (v1.11.1 for example) from master if we need to.

bump to v1.12.0. we can release hotfix from master if we need to

---

CHANGELOG.md
files/zlux/config/plugins/org.zowe.configjs.json
files/zlux/config/plugins/org.zowe.editor.json
files/zlux/config/plugins/org.zowe.terminal.proxy.json
files/zlux/config/plugins/org.zowe.terminal.tn3270.json
files/zlux/config/plugins/org.zowe.terminal.vt.json
files/zlux/config/plugins/org.zowe.zlux.appmanager.app.propview.json
files/zlux/config/plugins/org.zowe.zlux.auth.safsso.json
files/zlux/config/plugins/org.zowe.zlux.bootstrap.json
files/zlux/config/plugins/org.zowe.zlux.logger.json
files/zlux/config/plugins/org.zowe.zlux.ng2desktop.json
files/zlux/config/plugins/org.zowe.zlux.ng2desktop.settings.json
files/zlux/config/plugins/org.zowe.zlux.sample.angular.json
files/zlux/config/plugins/org.zowe.zlux.sample.iframe.json
files/zlux/config/plugins/org.zowe.zlux.sample.react.json
files/zlux/config/plugins/org.zowe.zosmf.workflows.json
files/zlux/config/zluxserver.json
manifest.json.template

Resolves https://github.com/zowe/zowe-install-packaging/issues/1245
Depends upon https://github.com/zowe/zlux-server-framework/pull/212
Uses https://github.com/zowe/zlux-server-framework/pull/212 to ensure that the built-in plugins always point to the ROOT_DIR of your Zowe install, wherever that is. An update script is needed to perform this one-time switch, which is in https://github.com/zowe/zlux-app-server/pull/123

Update default plugins to use ROOT_DIR relative path

---

files/zlux/config/zluxserver.json

Identical purpose to https://github.com/zowe/zlux-app-server/pull/104 but applied to our release config, not our dev config.
This changes the default app-server config to set the x-frame-options header to "sameorigin", preventing framing of apps at other domains, by default
This has been tested in dev config, so nothing new here except that it would be applied to release code.

Update default headers for x-frame-options

---

manifest.json.template

I'm been informed that a bunch of our components are pulling in the keyring-utilites repo, so I figured they are supposed to be in the source scans

Add keyring utilities source dependency

---

scripts/utils/zowe-copy-to-JES.sh
scripts/utils/zowe-install-xmem.sh

Fixes #1547, Fixes #1550 
1547
- stop copying SZWEAUTH and use the real thing
- make PARMLIB optional (SZWESAMP is default)
- do not assume script is called from within scripts/utils
1550
- comment out PROC test
---
STC JCL
---
update data set names in STC 
---
* Part: …

XMEM serve must use SZWEAUTH

---

playbooks/roles/start/tasks/main.yml

`REUSASID=YES` was introduced in v1.6 but the automation is not defining this extra parameter to start ZIS. This may cause potential shortage on common storage and eventually will require IPL on the system.
- Add `REUSASID=YES` when starting ZIS.

REUSASID is required to avoid ASID shortage

---

Jenkinsfile.nightly

Adding code so that if the install-tests called by nightly build fail, the build finishes as unstable rather than successful.

Add UNSTABLE result to Nightly build

---

Jenkinsfile.nightly

The code I committed yesterday to set the state of the build to UNSTABLE, caused the nightly build to skip the promote and slack message steps. 
To avoid this, I have implemented a boolean variable for checking the state of the tests, then that sets the state of the build at the end so as to not avoid the promote and message steps.

Fix nightly build skip of promote and message steps

---

playbooks/roles/zowe/tasks/uninstall_keyring.yml
playbooks/roles/zowe/tasks/uninstall_keyring_acf2.yml
playbooks/roles/zowe/tasks/uninstall_keyring_tss.yml
tests/installation/Jenkinsfile

Implements #1637 
- Add undo script for ACF2 keyring to ensure we start from a clean state each test run

Add keyring uninstall steps for ACF2

---

Jenkinsfile

Switching the account used for dockerhub from rsqa to ompzowe, as a more official sounding name to use.

Switching dockerhub account used for docker image publishing

---

manifest.json.template

**Related to**
Issue #1721 
**Changes being made**
Updating the source tag for vscode-extenions-for-zowe as it was missing the 'v' marker.

Update vscode-extension tag

---

Jenkinsfile

In this PR, a new stage is made to build docker for zlinux. I decided to make this a stage separate from docker for linux, so you can see progress better, but it's a very similar task with the exception that zlinux needs to do the actions over ssh, while the linux build happens within a docker node inside of our primary jenkins docker node.
The zlinux build completes more quickly than the linux build, since it's a separate system that is ssh into.
The result ends up on artifactory and optionally dockerhub. For artifactory, you can see the output here: https://zowe.jfrog.io/zowe/libs-snapshot-local/org/zowe/1.17.0-PR-1763/ where zlinux contains the string "s390x", while linux contains "amd64".

Add zlinux build to build process

---

playbooks/roles/configfmid/tasks/create_security_defn.yml

Further fix to #1614
- Set the security product correctly in configurefmid role, as well as configure

Set product properly on configurefmid.

---

playbooks/roles/configure/tasks/configure_instance.yml

Fixes #1800 
- Only inject ZWE token if x509 enabled

Only inject ZWEToken if x509 enabled

---

bin/utils/file-utils.sh
bin/utils/zowe-variable-utils.sh
tests/sanity/test/install/test-file-utils.js
tests/sanity/test/install/test-zowe-variable-utils.js

Part of #1803
- Update utils list separation to be comma delimited for consistency with the rest of the code

Switch list separation to commas for consistency

---

playbooks/roles/start/defaults/main.yml
tests/installation/Jenkinsfile

Implements #1809 
- Reduce number of retries to 10mins based on slack conversation
- Add --detectOpenHandles to try and find unfinished jest tests

Reduce global timeout

---

scripts/instance.template.env

Add two environment properties to make API Gateway connection limit configurable by Zowe users. Required by https://github.com/zowe/api-layer/pull/985

Add connection limit env properties

---

tests/installation/Jenkinsfile
tests/installation/src/__tests__/extended/node-versions/node-v14.ts

Part of #1830 
- Remove v6 tests and add v14 test to bundle
- Add v14 option and remove obsolete options from test configuration

Update node versions

---

Jenkinsfile
Jenkinsfile.release
playbooks/README.md
playbooks/roles/docker/defaults/main.yml

Depends upon: https://github.com/zowe/zowe-dockerfiles/pull/24
This is a change just to the docker image name, for the purpose of identifying its purpose and allowing the version number to be independent of the name.
This should not impact behavior.

Rename docker image

---

playbooks/host_vars/marist-1.yml
playbooks/roles/verify/defaults/main.yml

Fixes #1844 
- Update test matcher to only include .js files

Only run js test files

---

bin/zowe-setup-certificates.sh

- Call the keytool command directly rather than ‘save’ the command to a variable as this causes issues with the escaping of double quotes

Execute keytool command directly to fix escape issues

---

tests/installation/Jenkinsfile
tests/installation/src/__tests__/extended/node-versions/node-v12.ts
tests/sanity/test/utils-scripts/test-component-utils.js

Fixes test failures of `read_component_manifest` with node v12.16.1. This failure doesn't block Zowe from starting up properly. The output of `read_component_manifest` will be passed to shell script and encoding will be handled properly. But if return the node output directly to SSH command, like what test is doing, it's not readable.
- The direct output from …

fix test failures with node v12.16.1 and add v12.18.4 into test

---

manifest.json.template

Part of #1913 
- Downgrade caching service as 1.19.2 was failing tests

Downgrade caching service

---

smpe/bld/ptf.readme.htm
smpe/bld/smpe-service.sh

Fixes #1919
- add pre-req PTFs to sample ACCEPT job in PTF readme
- substitute & with &amp; in hold to avoid unintended interpretation by browswer
---
---
---
---

SMP/E install HTM is missing the prereqs list in the ACCEPT job

---

bin/internal/prepare-workspace.sh
bin/internal/start-component.sh
bin/utils/component-utils.sh
tests/sanity/test/utils-scripts/test-component-utils.js

Currently zowe runtime log will show deprecated messages like these:
- unable to determine validate script from component zss manifest, fall back to default bin/validate.sh
- unable to determine configure script from component zss manifest, fall back to default bin/configure.sh
- unable to determine …

surpress deprecated warnings for core components

---

scripts/instance.template.env

The caching service startup was failing because it needed to add two properties for a startup. The properties are added with the default values in this PR.

Introduce size of the Cache in the environment vavriables.

---

manifest.json.template

Changes in Imperative v4.11.0:
* Enhancement: Fixed plugin install commands which were broken in npm@7. [#457](https://github.com/zowe/imperative/issues/457)
* BugFix: Fixed incorrect formatting of code blocks in web help. [#535](https://github.com/zowe/imperative/issues/535)
Changes in Zowe CLI v6.26.0:
* Enhancement: Updated Imperative version to support npm@7. This fixes an error when installing plugins.

Update Zowe CLI components for 1.19.1 bundle

---

smpe/bld/ptf-split.rex
smpe/bld/smpe-service.sh

1. the HTML with PTF install instructions needs a small cosmetic tweak when we ship only 1 PTF
2. the build process is updated to halt the build when it is creating a different number of PTFs than listed in ptf-bucket.txt
Fixes 
- The HTML with PTF install instructions needs a small cosmetic tweak when we ship only 1 PTF.
- The build process is updated to …

PTF HTML cleanup, & build tweak to halt on unexpected PTF count

---

CHANGELOG.md
containers/server-bundle/Dockerfile
containers/server-bundle/run.sh
containers/server-bundle/run_inner.sh

Recent changes to the docker image to run as user=zowe presented an issue where mounted volumes might have group permissions that did not match the docker image due to the docker image not having the same groups.
However, users can control whether docker mounts are read or read-write regardless of file permissions, so if the volume is writable, zowe should be able to make use of group-level permissions. Therefore, this change assigns zowe to the group seen within each mount folder before starting the servers. This has no impact on the host system, its just aligning the container to be more compatible with the mounts. The …

Assign zowe docker user to same group as mounted volumes

---

containers/server-bundle/Dockerfile

Very small PR to fix an issue seen in 1.20 RCs: the s390x build is adding our run scripts without execute bit, therefore the docker image of s390x isnt working. This should fix it.

Explicitly set execute to prevent s390x build error

---

tests/installation/Jenkinsfile

Bundle test for keyring should lock all 3 servers it's testing.

missing locks for keyring test

---

Jenkinsfile.release

Mistakenly closed https://github.com/zowe/zowe-install-packaging/pull/2125
Reopening this to solve the same issue:
This PR is to resolve errors seen in the release output https://wash.zowe.org:8443/view/Zowe/job/zowe-promote-publish/job/staging/92
In it, the source images are not found due to seemingly a typo, as https://zowe.jfrog.io/artifactory/libs-snapshot-local/org/zowe/1.21.0-SNAPSHOT/serv[…]er-bundle.sources.amd64-1.21.0-snapshot-826-20210427215530.tar exists, "sources" vs source.
Secondarily, the code did not check if there were any sources to publish before issuing the docker commands, leading to failure later on too.

Fix for publishing source

---

files/zlux/config/plugins/org.zowe.zlux.agent.json
files/zlux/config/plugins/org.zowe.zlux.json
manifest.json.template

Without relativeTo plugins for our two new meta-plugins that add proper swagger support, the plugins break if ROOT_DIR is changed.
With the addition of the relativeTo pointers here, the plugins become portable just as our other plugins are, so this is the behavior we want.

Fix portability of swagger support plugins

---

bin/zowe-configure-instance.sh
install/zowe-install.sh
scripts/instance.template.env

This is a partial reversion to accompany https://github.com/zowe/zowe-install-packaging/pull/2216 by removing references to pluginlib. the rest of the code for better or worse can record locations of loadlib, parmlib in non-smpe settings and allow manual entry for smpe which will help zis plugin automation down the line.

Remove pluginlib occurrences temporarily

---

bin/zowe-configure-component.sh

Fixes https://app.zenhub.com/workspaces/web-ui-squad-60549e46bd10bf00115d1f69/issues/zowe/zlux/670
- Automates ZIS plugin discovery & install ZIS libs to the right ZWES datasets using the ZIS plugin install script. The ZIS libs, and how to customize where they are pointed to, is described in the doc change here: …

Automate ZIS plugin check & install at configuration step

---

.github/workflows/zowe-launch-scripts-images.yml

Another dummy workflow to enable manual build.

dummy ompzowe/zowe-launch-scripts workflow

---

Jenkinsfile
manifest.json.template

The library necessary for building the PAX file going forward from 1.24 release is added. AT-TLS functionality depends on this library.

Add link to the common java library

---

containers/kubernetes/workloads/app-server-deployment.yaml
files/zlux/config/plugins/org.zowe.configjs.json
files/zlux/config/plugins/org.zowe.editor.json
files/zlux/config/plugins/org.zowe.explorer-ip.json
files/zlux/config/plugins/org.zowe.terminal.proxy.json
files/zlux/config/plugins/org.zowe.terminal.tn3270.json
files/zlux/config/plugins/org.zowe.terminal.vt.json
files/zlux/config/plugins/org.zowe.zlux.agent.json
files/zlux/config/plugins/org.zowe.zlux.appmanager.app.propview.json
files/zlux/config/plugins/org.zowe.zlux.auth.safsso.json
files/zlux/config/plugins/org.zowe.zlux.bootstrap.json
files/zlux/config/plugins/org.zowe.zlux.json
files/zlux/config/plugins/org.zowe.zlux.logger.json
files/zlux/config/plugins/org.zowe.zlux.ng2desktop.json
files/zlux/config/plugins/org.zowe.zlux.ng2desktop.settings.json
files/zlux/config/plugins/org.zowe.zlux.sample.angular.json
files/zlux/config/plugins/org.zowe.zlux.sample.iframe.json
files/zlux/config/plugins/org.zowe.zlux.sample.react.json
files/zlux/config/plugins/org.zowe.zosmf.workflows.json

This PR enables the app-server container to work by having the plugins relative paths reference the the zlux location, rather than the ROOT_DIR which is not the same in a container as it is on z/os.

App server container support

---

CHANGELOG.md
bin/zowe-configure-instance.sh

Certain useful scripts for app-server and zss are not currently available in the instance directory. This could lead to users finding the scripts in component directories, using them, and then possibly later having a problem if we decide to move or rename files within component directories, since …

Add missing scripts

---

files/jcl/ZWENOSSO.jcl

If jwtsecret is imported from USS keystore, it may not have private key. When we delete token bound with this cert, we will see error:
```
IRRD173I Certificate with sequence number 00000001 does not have a private key in RACF. The request is not processed.
```
- Add `FORCE` when deleting token.

force is required if private key is not imported into racf

---

manifest.json.template

* Updated Imperative, Zowe CLI, and CICS/DB2/IMS/MQ plug-ins to point to next branch
* Removed Secure Credential Store which is no longer supported in vNext
* No changes to perf-timing and FTP plug-in which don't have next branches

Update sourceDependencies for Zowe CLI v2

---

manifest.json.template

To include fix of https://github.com/zowe/launcher/pull/31

update launcher version to 0.0.8

---

manifest.json.template

This aligns the manifest of v2 to match the current staging name scheme for zlux-core.

Update zlux-core manifest

---

.dependency/zwe_doc_generation/index.js
.dependency/zwe_doc_generation/md-content.js
.github/workflows/zwe-doc-generation.yml

- Fixes a formatting bug with the examples not showing as code
- Improves `zwe` server command reference generation for the docs-site. The automation is fixed, [this action run](https://github.com/zowe/zowe-install-packaging/runs/5606036808?check_suite_focus=true) created [this PR to docs-site](https://github.com/zowe/docs-site/pull/2076) successfully.
- Adds a nav menu to the sidebar for the reference. Attached is a video created using a local version of the docs site to show the new nav menu.
https://user-images.githubusercontent.com/14897740/159085150-b2a4ff42-54ce-43b4-b3cd-badf46ece122.mov
PR with corresponding docs-site changes (sidebars.js update and the new documentation files): https://github.com/zowe/docs-site/pull/2077

Improve zwe documentation generation
